### ISSUE TITLE
Installation of manim in Apple BigSur (M1 processor)

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#1004]
Currently, installing manim on the BigSur OS following these instructions: https://docs.manim.community/en/latest/installation/mac.html
gives the following error:
```console
$ manim -h
Traceback (most recent call last):
  File "/Users/kolibril/opt/anaconda3/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/manim/__init__.py", line 20, in <module>
    from .animation.composition import *
  File "/Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/manim/animation/composition.py", line 8, in <module>
    from ..scene.scene import Scene
  File "/Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/manim/scene/scene.py", line 21, in <module>
    from ..camera.camera import Camera
  File "/Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/manim/camera/camera.py", line 14, in <module>
    import cairo
  File "/Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: dlopen(/Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/cairo/_cairo.cpython-38-darwin.so, 2): Symbol not found: _cairo_append_path
  Referenced from: /Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/cairo/_cairo.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/kolibril/opt/anaconda3/lib/python3.8/site-packages/cairo/_cairo.cpython-38-darwin.so
```

any ideas how to fix this?

**Comment by naveen521kk** [comment]
At first, it looks like you are using anaconda, I don't know exactly how to fix this because they have a separate package manager (conda) which provides some system libraries like Cairo. Which makes me ask how did you install Pycairo or rather manim?

Two, Brew has already build Cairo https://formulae.brew.sh/formula/cairo#default on Big Sur, so I think using that would be better. So, what I mean is stop using anaconda and install python from Brew and then run manim on that as specified in the docs. Things should be fixed IMO.

**Comment by kolibril13** [comment]
Thanks a lot for this idea, now I removed anaconda and tried pip3 install manim with the brew version of python, and I get this:
```
Collecting colour
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting networkx<3.0,>=2.5
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting Pillow
  Using cached Pillow-8.1.0.tar.gz (44.9 MB)
Collecting manimpango<0.3.0,>=0.2.0
  Using cached manimpango-0.2.0.tar.gz (89 kB)
Collecting pydub
  Using cached pydub-0.24.1-py2.py3-none-any.whl (30 kB)
Collecting pygments
  Using cached Pygments-2.7.4-py3-none-any.whl (950 kB)
Collecting scipy
  Using cached scipy-1.6.0.tar.gz (27.3 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-build-env-yusrl9u4/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'numpy==1.16.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"'' 'numpy; python_version>='"'"'3.10'"'"'' 'pybind11>=2.4.3'
       cwd: None
  Complete output (915 lines):
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting setuptools<=51.0.0
    Using cached setuptools-51.0.0-py3-none-any.whl (785 kB)
  Collecting Cython>=0.29.18
    Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
    ```

**Comment by naveen521kk** [comment]
Why does it compile scipy and not use its wheels?
Also, what does this print for you using homebrew python?
```sh
python -c "import distutils.util; print(distutils.util.get_platform())"
```

If pip doesn't work good try using brew for scipy also
```sh
brew install scipy
```

**Comment by kolibril13** [comment]
> ```shell
> python -c "import distutils.util; print(distutils.util.get_platform())"
> ```
 
gives me `macosx-11-arm64`

I dont get an scipy error anymore, the new error is now:
```console
Building wheels for collected packages: manimpango, pycairo, Pillow
  Building wheel for manimpango (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/setup.py'"'"'; __file__='"'"'/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-wheel-lhky1c_l
       cwd: /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-arm64-3.9
  creating build/lib.macosx-11-arm64-3.9/manimpango
  copying manimpango/__init__.py -> build/lib.macosx-11-arm64-3.9/manimpango
  copying manimpango/cmanimpango.pxd -> build/lib.macosx-11-arm64-3.9/manimpango
  running build_ext
  building 'manimpango.cmanimpango' extension
  creating build/temp.macosx-11-arm64-3.9
  creating build/temp.macosx-11-arm64-3.9/private
  creating build/temp.macosx-11-arm64-3.9/private/var
  creating build/temp.macosx-11-arm64-3.9/private/var/folders
  creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3
  creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn
  creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T
  creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7
  creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878
  creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/tcl-tk/include -I/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango/cmanimpango.c -o build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango/cmanimpango.o
  /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango/cmanimpango.c:643:10: fatal error: 'glib.h' file not found
  #include "glib.h"
           ^~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for manimpango
  Running setup.py clean for manimpango
  Building wheel for pycairo (PEP 517) ... done
  Created wheel for pycairo: filename=pycairo-1.20.0-cp39-cp39-macosx_11_0_arm64.whl size=91698 sha256=5b8f5ad87c385b5005069434901c6b43fd97d5137cc0c250e99852321d6779db
  Stored in directory: /Users/jan-hendrik/Library/Caches/pip/wheels/41/fe/c0/bf4275a9f9326a7e65da52c9d48488d3ac8c1f5bc4bf83024a
  Building wheel for Pillow (setup.py) ... done
  Created wheel for Pillow: filename=Pillow-8.1.0-cp39-cp39-macosx_11_0_arm64.whl size=529011 sha256=10b8c833a34d1616e9369cf2a9c35b2b99f00372c75390f0fb40a973ddd1a5bb
  Stored in directory: /Users/jan-hendrik/Library/Caches/pip/wheels/e4/6d/51/45e06952711dacab3f8e02131989551d76b6b97f7a506e71ff
Successfully built pycairo Pillow
Failed to build manimpango
Installing collected packages: typing-extensions, pygments, decorator, commonmark, colorama, tqdm, rich, pydub, pycairo, Pillow, networkx, manimpango, colour, manim
    Running setup.py install for manimpango ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/setup.py'"'"'; __file__='"'"'/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-record-opncic2z/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/manimpango
         cwd: /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/
    Complete output (26 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11-arm64-3.9
    creating build/lib.macosx-11-arm64-3.9/manimpango
    copying manimpango/__init__.py -> build/lib.macosx-11-arm64-3.9/manimpango
    copying manimpango/cmanimpango.pxd -> build/lib.macosx-11-arm64-3.9/manimpango
    running build_ext
    building 'manimpango.cmanimpango' extension
    creating build/temp.macosx-11-arm64-3.9
    creating build/temp.macosx-11-arm64-3.9/private
    creating build/temp.macosx-11-arm64-3.9/private/var
    creating build/temp.macosx-11-arm64-3.9/private/var/folders
    creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3
    creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn
    creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T
    creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7
    creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878
    creating build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/opt/homebrew/opt/tcl-tk/include -I/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango/cmanimpango.c -o build/temp.macosx-11-arm64-3.9/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango/cmanimpango.o
    /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/manimpango/cmanimpango.c:643:10: fatal error: 'glib.h' file not found
    #include "glib.h"
             ^~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/setup.py'"'"'; __file__='"'"'/private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-install-jbhzp8d7/manimpango_a4c7569002b0449ab8f39e8cb1050878/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c3/3bzrl3qx043bknt1ycn3fcym0000gn/T/pip-record-opncic2z/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/manimpango Check the logs for full command output.
```

**Comment by naveen521kk** [comment]
Well, it is arm and everything should be compiled from source or should depend on Brew, no one build wheels for this sadly.

What you can do for that error on manimpango is run 
```sh
brew install pango
```
and then just that will work as usual.

**Comment by kolibril13** [comment]
Now, the installation is successful (after running `brew install pango`), however when I try to run manim, I get this message:
```
$ manim -h   
zsh: bus error  manim -h
```

**Comment by naveen521kk** [comment]
> Now, the installation is successful (after running brew install pango), however when I try to run manim, I get this message:

Possibly because of a problem with your shell or terminal. I am closing this issue as it is fixed.
