### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Shantanu-Manim** [ManimCommunity/manim#1057]
I am trying to make a simple animation but i am messing it up with the commands while trying to rendering the output of the command is try this instead of this my code is
`from manim import *`

` class WhatIsCONFIG(Scene):`
    `def construct(self):`
       `object_1 = Text("Object 1")`
       `object_2 = Square()`
        `vector = [1, 1, 0]`
        `self.play(Write(object_1), run_time=3)`
        `self.wait(3)`
        `self.play(object_1.scale, 3)`
        `self.play(ReplacementTransform(object_1, object_2))`
        `self.play(object_2.shift(object_2, vector))`
        `self.wait()`
![code](https://user-images.githubusercontent.com/79604276/109324278-73424c00-787a-11eb-9596-c9a27778d725.png)
the error which it is showing is

 Traceback (most recent call last):
  File "C:\ManiM\manim-master\manim\scene\scene.py", line 626, in compile_animations
    animations.append(prepare_animation(arg))
  File "C:\ManiM\manim-master\manim\animation\animation.py", line 231, in prepare_animation
    raise TypeError(f"Object {anim} cannot be converted to an animation")
TypeError: Object <bound method Mobject.scale of Text('Object 1')> cannot be converted to an animation

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):

 

  File "C:\ManiM\manim-master\manim\__main__.py", line 95, in main

    scene.render()

   File "C:\ManiM\manim-master\manim\scene\scene.py", line 169, in render

    self.construct()
 

  File "C:\ManiM\manim-master\Manim_TUT\1.py", line 11, in construct

    self.play(object_1.scale, 3)
 

 File "C:\ManiM\manim-master\manim\scene\scene.py", line 763, in play

    self.renderer.play(self, *args, **kwargs)
  File "C:\ManiM\manim-master\manim\renderer\cairo_renderer.py", line 12, in wrapper
    func(self, scene, *args, **kwargs)
  File "C:\ManiM\manim-master\manim\utils\caching.py", line 23, in wrapper
    animations = scene.compile_animations(*args, **kwargs)
  File "C:\ManiM\manim-master\manim\scene\scene.py", line 629, in compile_animations
    raise TypeError(
TypeError: Passing Mobject methods to Scene.play is no longer supported. Use Mobject.animate instead
![error1_py](https://user-images.githubusercontent.com/79604276/109324893-46daff80-787b-11eb-9e7d-fa9ffd4b2c7e.png)
help me sort this problem
and please can you tell me where can i find the different commands in the manim module of this 
repository because i am again and again disturbing you soryy for that
what changes do ineed to make in code

**Comment by Shantanu-Manim** [comment]
and i just checked in media its showing this
![config](https://user-images.githubusercontent.com/79604276/109339728-1355a080-788e-11eb-926d-e7d8746b6ea2.png)
there
![mp4](https://user-images.githubusercontent.com/79604276/109339880-4ef06a80-788e-11eb-9e98-0b9f55da96b4.png)
these videos are working
please tell me then first why it should typeError
TypeError: Object <bound method Mobject.scale of Text('Object 1')> cannot be converted to an animation
TypeError: Passing Mobject methods to Scene.play is no longer supported. Use Mobject.animate instead
