### ISSUE TITLE
malloc failed when rendering 4k

### ISSUE THREAD

**Issue by Gutza** [ManimCommunity/manim#1089]
## Description of bug / unexpected behavior
I'm encountering an unexpected memory allocation error attempting to render a simple scene at 4k on a computer which really shouldn't struggle with this task.

## Expected behavior
`manim malloc.py malloc -qk` should render the scene

## How to reproduce the issue
<details><summary>Code for reproducing the problem</summary>

```py
from manim import *

class malloc(GraphScene, MovingCameraScene):
    def __init__(self, **kwargs):
        GraphScene.__init__(
            self,
            graph_origin=[-1,0,0],
            x_axis_width=10,
            x_min=-5,
            x_max=+5,
            y_min=-1.5,
            y_max=+1.5,
            axes_color=GREEN,
            x_labeled_nums=range(-4, 5),
            y_labeled_nums=range(-1, 2),
            **kwargs
        )
        self.function_color = RED

    def setup(self):
        GraphScene.setup(self)
    
    def construct(self):
        INTERSECTION_DOT_SIZE = 0.06

        self.camera.background_color = "#101010"
        self.camera.frame.set_width(6).move_to([-1, 0, 0])

        self.wait()

        firstPoint = Dot(
            point=[-1, 0, 0],
            radius=INTERSECTION_DOT_SIZE
        )
        self.play(ShowCreation(firstPoint))
        self.wait()

        secondPoint = Dot(
            point=[0, 0, 0],
            radius=INTERSECTION_DOT_SIZE
        )
        self.play(
            self.camera.frame.animate.move_to([-0.5, 0, 0]),
            ShowCreation(secondPoint)
        )
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
[03/09/21 06:39:59] DEBUG    creating dummy animation                                                                                                                                          animation.py:63                    DEBUG    Hashing ...                                                                                                                                                        hashing.py:239                    DEBUG    Hashing done in 0.007355 s.                                                                                                                                        hashing.py:252                    DEBUG    Hash generated :  1279063743_4180579860_223132457                                                                                                                  hashing.py:256                    INFO     Animation 0 : Using cached data (hash : 1279063743_4180579860_223132457)                                                                                            caching.py:39                    DEBUG    List of the first few animation hashes of the scene: ['1279063743_4180579860_223132457']                                                                            caching.py:48                    DEBUG    Hashing ...                                                                                                                                                        hashing.py:239                    DEBUG    Hashing done in 0.004655 s.                                                                                                                                        hashing.py:252                    DEBUG    Hash generated :  1279063743_254726783_3982383373                                                                                                                  hashing.py:256                    DEBUG    List of the first few animation hashes of the scene: ['1279063743_4180579860_223132457', '1279063743_254726783_3982383373']                                         caching.py:48Animation 1: ShowCreation(Dot):   0%|                                                                                                                                                 | 0/60 [00:00<?, ?it/s]x264 [error]: malloc of size 43687840 failed
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height



Traceback (most recent call last):
  File "c:\python38\lib\site-packages\manim\__main__.py", line 94, in main
    scene.render()
  File "c:\python38\lib\site-packages\manim\scene\scene.py", line 169, in render
    self.construct()
  File "M:\Personal\2021 Dancing compass\malloc.py", line 37, in construct
    self.play(ShowCreation(firstPoint))
  File "c:\python38\lib\site-packages\manim\scene\scene.py", line 763, in play
    self.renderer.play(self, *args, **kwargs)
  File "c:\python38\lib\site-packages\manim\renderer\cairo_renderer.py", line 12, in wrapper
    func(self, scene, *args, **kwargs)
  File "c:\python38\lib\site-packages\manim\utils\caching.py", line 52, in wrapper
    func(self, scene, *args, **kwargs)
  File "c:\python38\lib\site-packages\manim\renderer\cairo_renderer.py", line 40, in wrapper
    func(self, scene, *args, **kwargs)
  File "c:\python38\lib\site-packages\manim\renderer\cairo_renderer.py", line 79, in play
    scene.play_internal()
  File "c:\python38\lib\site-packages\manim\scene\scene.py", line 844, in play_internal
    self.renderer.render(self, self.moving_mobjects)
  File "c:\python38\lib\site-packages\manim\renderer\cairo_renderer.py", line 123, in render
    self.add_frame(self.get_frame())
  File "c:\python38\lib\site-packages\manim\renderer\cairo_renderer.py", line 153, in add_frame
    self.file_writer.write_frame(frame)
  File "c:\python38\lib\site-packages\manim\scene\scene_file_writer.py", line 277, in write_frame
    self.writing_process.stdin.write(frame.tostring())
OSError: [Errno 22] Invalid argument
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 10 20H2
- RAM: 32 GB
- Python version (`python/py/python3 --version`): Python 3.8.3
- Installed modules (provide output from `pip list`):
```
Package           Version
----------------- -------
astroid           2.5
backcall          0.2.0
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
cycler            0.10.0
decorator         4.4.2
glcontext         2.3.2
ipython           7.21.0
ipython-genutils  0.2.0
isort             5.7.0
jedi              0.18.0
kiwisolver        1.3.1
lazy-object-proxy 1.5.2
manim             0.3.0
manimgl           1.0.0
ManimPango        0.2.3
mapbox-earcut     0.12.10
matplotlib        3.3.4
mccabe            0.6.1
moderngl          5.6.4
moderngl-window   2.3.0
mpmath            1.2.1
multipledispatch  0.6.0
networkx          2.5
numpy             1.20.1
parso             0.8.1
pickleshare       0.7.5
Pillow            8.1.0
pip               21.0.1
progressbar       2.5
prompt-toolkit    3.0.16
pycairo           1.20.0
pydub             0.24.1
pyglet            1.5.15
Pygments          2.8.0
pylint            2.7.1
PyOpenGL          3.1.5
pyparsing         2.4.7
pyreadline        2.1
pyrr              0.10.3
python-dateutil   2.8.1
PyYAML            5.4.1
rich              6.2.0
rope              0.18.0
scipy             1.6.1
screeninfo        0.6.7
setuptools        41.2.0
six               1.15.0
sympy             1.7.1
toml              0.10.2
tqdm              4.58.0
traitlets         5.0.5
typing-extensions 3.7.4.3
validators        0.18.2
wcwidth           0.2.5
wheel             0.36.2
wrapt             1.12.1
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): MikTeX 21.2
+ Installed LaTeX packages: it's difficult to capture, there are several pages. I will provide these if needed.

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 2.2.2
built on May 22 2014 19:56:44 with gcc 4.8.2 (GCC)
configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
libavutil      52. 66.100 / 52. 66.100
libavcodec     55. 52.102 / 55. 52.102
libavformat    55. 33.100 / 55. 33.100
libavdevice    55. 10.100 / 55. 10.100
libavfilter     4.  2.100 /  4.  2.100
libswscale      2.  5.102 /  2.  5.102
libswresample   0. 18.100 /  0. 18.100
libpostproc    52.  3.100 / 52.  3.100
```
</details>

**Comment by kilacoda** [comment]
Can't reproduce. 🙁 Maybe try restarting your computer? It doesn't seem to be a manim problem but rather a system specific problem.

**Comment by Gutza** [comment]
I have restarted my computer several times since I first encountered this issue. I also tried increasing my paging file size. to no avail. I have no issues in other applications. Could it be relevant that I'm doing this on an AMD Ryzen CPU?

**Comment by Darylgolden** [comment]
Have you tried running it at a lower quality? Does it work?

**Comment by kilacoda** [comment]
Your ffmpeg version seems to be quite old v(yours-> `2.2.2`, current -> `4.3.2` ). Maybe try updating that?

**Comment by Gutza** [comment]
Yes, upgrading ffmpeg fixed it! For future reference, please note I also had to manually clear the cache (removed all partial mp4 files), because some of them were empty (0 bytes), but manim thought they were legitimate files and tried to use them. For the record, generating files with a smaller size did work (including -qh).
