### ISSUE TITLE
Docs should include installation instructions for Colab

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1135]
## Enhancement proposal
The docs should include installation instructions for Colab, namely running this:
```
!sudo apt install libcairo2-dev ffmpeg texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa libpango1.0-dev
!pip install manim
!pip install IPython --upgrade
```
After the cell has run, Colab will prompt you to restart the runtime. Click the button at the bottom of the cell output, then run
```
from manim import *
```
I would add this to docs myself, but for some reason I can't get sphinx to work properly.
## Additional comments
The 0.3.0 example notebook no longer runs; it may be worth retroactively fixing it.

**Comment by dbosk** [comment]
```
$ pip3 install manim
Collecting manim                                                                  
  Downloading manim-0.4.0-py3-none-any.whl (285 kB)                               
     |████████████████████████████████| 285 kB 5.1 MB/s                           
Collecting manimpango<0.3.0,>=0.2.0                                               
  Downloading ManimPango-0.2.4.tar.gz (26 kB)
  Installing build dependencies ... done                                          
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:                                  
   command: /usr/bin/python3 /tmp/tmpj5agljb9 get_requires_for_build_wheel /tmp/tm
prosk7zdd                                                                         
       cwd: /tmp/pip-install-3ggshtfg/manimpango                                  
  Complete output (33 lines):                                                     
  Package pangocairo was not found in the pkg-config search path.                 
  Perhaps you should add the directory containing `pangocairo.pc'                 
  to the PKG_CONFIG_PATH environment variable                                     
  No package 'pangocairo' found                                                   
  Traceback (most recent call last):                                              
    File "setup.py", line 124, in check_min_version                               
      check_call(command, stdout=subprocess.DEVNULL)                              
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call              
      raise CalledProcessError(retcode, cmd)                                      
  subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atle
ast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.           
                                                                                  
  During handling of the above exception, another exception occurred:             
                                                                                  
  Traceback (most recent call last):                                              
    File "/tmp/tmpj5agljb9", line 280, in <module>                                
      main()                                                                      
    File "/tmp/tmpj5agljb9", line 263, in main                                    
      json_out['return_val'] = hook(**hook_input['kwargs'])                       
    File "/tmp/tmpj5agljb9", line 114, in get_requires_for_build_wheel            
      return hook(config_settings)                                                
    File "/tmp/pip-build-env-r0s0d2yc/overlay/lib/python3.8/site-packages/setuptoo
ls/build_meta.py", line 154, in get_requires_for_build_wheel                      
      return self._get_build_requires(                                            
    File "/tmp/pip-build-env-r0s0d2yc/overlay/lib/python3.8/site-packages/setuptoo
ls/build_meta.py", line 135, in _get_build_requires                               
      self.run_setup()                                                            
    File "/tmp/pip-build-env-r0s0d2yc/overlay/lib/python3.8/site-packages/setuptoo
ls/build_meta.py", line 258, in run_setup                                         
      super(_BuildMetaLegacyBackend,                                              
    File "/tmp/pip-build-env-r0s0d2yc/overlay/lib/python3.8/site-packages/setuptoo
ls/build_meta.py", line 150, in run_setup                                         
      exec(compile(code, __file__, 'exec'), locals())                             
    File "setup.py", line 190, in <module>                                        
      _pkg_config.check_min_version(MINIMUM_PANGO_VERSION)                        
    File "setup.py", line 127, in check_min_version                               
      raise RequiredDependencyException(f"{self.name} >= {version} is required")  
  __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required          
  ----------------------------------------                                        
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpj5agljb9 g
et_requires_for_build_wheel /tmp/tmprosk7zdd Check the logs for full command outpu
t.
```
Resolved by
```bash
$ sudo apt install libpango1.0-dev libcairo2-dev
```

**Comment by Darylgolden** [comment]
I believe the 2 dependencies are installed in the `sudo apt install` statement, did you try to run the code block in entirety?

**Comment by dbosk** [comment]
Sorry, my comment was just to support the need for your issue. I went to 
the README, followed the installation instructions and ran into that 
problem. Your issue helped me resolve the problem. (But I just needed 
those two as I already have TeX installed.)

**Comment by Darylgolden** [comment]
Ah, I see. I misinterpreted your comment.

**Comment by dbosk** [comment]
Well, the original was very limited in words 😁 But I've clarified it.On 25 Mar 2021 14:37, Darylgolden ***@***.***> wrote:
Ah, I see. I misinterpreted your comment.
