### ISSUE TITLE
Version checker throws an error when manim is run without internet

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim#1365]
## Description of bug / unexpected behavior
Title.

## Expected behavior
Version checker should just log that the version can't be checked, and not produce a traceback.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
C:\Users\Daryl\manim-dev\manim>manim -p test.py
Manim Community v0.4.0

1: Become
2: BecomePoints
3: BecomePointsScene
4: BecomeStyle
5: BecomeStyle2
6: Image

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)
Choice(s):  6
[04/19/21 10:55:41] INFO                                                                        scene_file_writer.py:585
                             File ready at C:\Users\Daryl\manim-dev\manim\media\images\test\Ima
                             ge_ManimCE_v0.4.0.png

                    INFO     Rendered Image                                                                 scene.py:199
                             Played 0 animations
                    INFO     Previewed File at:                                                           file_ops.py:98
                             C:\Users\Daryl\manim-dev\manim\media\images\test\Image_ManimCE_v0.4.0.png
Traceback (most recent call last):
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\Scripts\manim", line 5, in <module>
    main()
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Daryl\AppData\Local\pypoetry\Cache\virtualenvs\manim-WZ_QM4hs-py3.9\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Daryl\manim-dev\manim\manim\cli\render\commands.py", line 166, in render
    stable = req_info.json()["info"]["version"]
AttributeError: 'dict' object has no attribute 'json'
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by Darylgolden** [comment]
Was added in #1237. Pinging @RickyC0626 as the PR author.

**Comment by naveen521kk** [comment]
Should be simple enough to do. It is as simple as running that line only when the previous one succeeded. https://github.com/ManimCommunity/manim/blob/master/manim/cli/render/commands.py#L166
Marking it as a Good First Issue and it must be fixed ASAP.

**Comment by CallMeMisterOwl** [comment]
Made a PR https://github.com/ManimCommunity/manim/pull/1368
