### ISSUE TITLE
Tex error!

### ISSUE THREAD

**Issue by loot-06** [ManimCommunity/manim#1543]
Full Code
```python
from manim import *

class TestKorean(Scene):
    def construct(self):
        Korean = Tex(r"테스트입니다") # it means "this is test"
        self.play(Write(Korean))

TestKorean().render()
```

Full Traceback
```
G:\Manim_PPJ\venv\Scripts\python.exe G:/Manim_PPJ/test.py
Traceback (most recent call last):
  File "G:/Manim_PPJ/test.py", line 9, in <module>
    TestKorean().render()
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\scene\scene.py", line 199, in render
    self.construct()
  File "G:/Manim_PPJ/test.py", line 5, in construct
    Korean = Tex(r"테스트입니다")
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 577, in __init__
    MathTex.__init__(
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 448, in __init__
    raise compilation_error
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 426, in __init__
    SingleStringMathTex.__init__(
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\mobject\svg\tex_mobject.py", line 259, in __init__
    file_name = tex_to_svg_file(
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\utils\tex_file_writing.py", line 44, in tex_to_svg_file
    dvi_file = compile_tex(
  File "G:\Manim_PPJ\venv\lib\site-packages\manim\utils\tex_file_writing.py", line 173, in compile_tex
    log = f.readlines()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 6431: illegal multibyte sequence

Process finished with exit code 1
```

**Comment by clarfonthey** [comment]
I ran this and got a better error:

```
[05/23/21 20:37:17] ERROR    LaTeX compilation error! latex reports:                       tex_file_writing.py:178
                    ERROR    ! Package inputenc Error: Unicode character 테 (U+D14C)       tex_file_writing.py:189

                    ERROR    (inputenc)                not set up for use with LaTeX.      tex_file_writing.py:189

                    ERROR                                                                  tex_file_writing.py:189

                    ERROR    See the inputenc package documentation for explanation.       tex_file_writing.py:189
```

Most likely, you need to add the right packages to a template to enable typesetting of Korean characters. See: https://docs.manim.community/en/stable/reference/manim.mobject.svg.tex_mobject.html

Here's an example I managed to get working:

```python
from manim import *

class TestKorean(Scene):
    def construct(self):
        Korean = Tex(r"테스트입니다", tex_template=TexTemplateLibrary.ctex) # it means "this is test"
        self.play(Write(Korean))

TestKorean().render()
```

Additionally on my system I had to install the Korean texlive packages.

Maybe we should have a better error for this -- if compilation fails and there are characters that would require xelatex, maybe point the user to them.
