### ISSUE TITLE
NumberLine error

### ISSUE THREAD

**Issue by kcyzy** [ManimCommunity/manim#1785]
In line 160, number_line.py, there is an undefined method.
![{CMD)NBX$4}$E 6$ 4H0))L](https://user-images.githubusercontent.com/33566397/125157829-b05f0900-e19f-11eb-8d5a-4f264d88259c.png)
When user tries to create a number line with numbers, the program makes an error.

**Comment by kcyzy** [comment]
By the way, there aren't even parentheses

**Comment by kcyzy** [comment]
By the way, there aren't even parentheses

**Comment by Darylgolden** [comment]
Hi! Can you provide more details? What code will result in this error and what traceback would they get?

**Comment by hydrobeam** [comment]
Hey! That's not a method, that's an attribute which is initialized on creation of the `NumberLine`. Also, that code doesn't seem to be  from the latest version of manim.

**Comment by kcyzy** [comment]
OK,I create a new demo.
![FV3 2L}KKBV6S%R _)EATA2](https://user-images.githubusercontent.com/33566397/125158081-34fe5700-e1a1-11eb-8d44-bc8d665863e9.png)
If I remove the comment in number_line.py, the console will output a report like this:

**Comment by kcyzy** [comment]
> Hey! That's not a method, that's an attribute which is initialized on creation of the `NumberLine`. Also, that code doesn't seem to be from the latest version of manim.

Thank you.Maybe I should update my version

**Comment by hydrobeam** [comment]
Well there are other problems with your code, namely that you're using manimgl, but with manimce code. The two versions of manim are generally incompatible with each other. See the manimce docs for relevant instructions: 

https://docs.manim.community/

**Comment by kcyzy** [comment]
The report:
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\manimlib\__main__.py", line 17, in main
    scene.run()
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\manimlib\scene\scene.py", line 75, in run
    self.construct()
  File "map.py", line 7, in construct
    axis=NumberLine(
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\manimlib\mobject\number_line.py", line 74, in __init__   
    self.add_numbers(excluding=self.numbers_to_exclude)
  File "c:\users\administrator\appdata\local\programs\python\python38-32\lib\site-packages\manimlib\mobject\number_line.py", line 160, in add_numbers
    if x in self.numbers_to_exclude:
TypeError: argument of type 'NoneType' is not iterable
===========================================
Poor access speed
(糟糕的访问速度)
