### ISSUE TITLE
PointWithTrace example fails with opengl renderer

### ISSUE THREAD

**Issue by ryanmccauley211** [ManimCommunity/manim#1925]
## Description of bug / unexpected behavior

Running the below PointWithTrace example fails with `KeyError: 'points'` when using the opengl renderer

```py
class PointWithTrace(Scene):
    def construct(self):
        path = VMobject()
        dot = Dot()
        path.set_points_as_corners([dot.get_center(), dot.get_center()])
        def update_path(path):
            previous_path = path.copy()
            previous_path.add_points_as_corners([dot.get_center()])
            path.become(previous_path)
        path.add_updater(update_path)
        self.add(path, dot)
        self.play(Rotating(dot, radians=PI, about_point=RIGHT, run_time=2))
        self.wait()
        self.play(dot.animate.shift(UP))
        self.play(dot.animate.shift(LEFT))
        self.wait()
```

## How to reproduce the issue

Run example with opengl renderer

<details><summary>Code for reproducing the problem</summary>

```py
class PointWithTrace(Scene):
    def construct(self):
        path = VMobject()
        dot = Dot()
        path.set_points_as_corners([dot.get_center(), dot.get_center()])
        def update_path(path):
            previous_path = path.copy()
            previous_path.add_points_as_corners([dot.get_center()])
            path.become(previous_path)
        path.add_updater(update_path)
        self.add(path, dot)
        self.play(Rotating(dot, radians=PI, about_point=RIGHT, run_time=2))
        self.wait()
        self.play(dot.animate.shift(UP))
        self.play(dot.animate.shift(LEFT))
        self.wait()
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
Manim Community v0.8.0

Traceback (most recent call last):
╭──────────────────────────────────────────────────────────────────────────────╮
│ File                                                                         │
│"/Users/ryan/PycharmProjects/manim-community/manim/cli/render/commands.py",   │
│line 109, in render                                                           │
│    106                     scene_classes = scene_classes_from_file(file)     │
│    107                     SceneClass = scene_classes[0]                     │
│    108                     scene = SceneClass(renderer)                      │
│  ❱ 109                     status = scene.render()                           │
│    110                     if status:                                        │
│    111                         continue                                      │
│    112                     else:                                             │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/scene/scene.py", line│
│215, in render                                                                │
│     212         """                                                          │
│     213         self.setup()                                                 │
│     214         try:                                                         │
│  ❱  215             self.construct()                                         │
│     216         except EndSceneEarlyException:                               │
│     217             pass                                                     │
│     218         except RerunSceneException as e:                             │
│ File "../scenes/playground.py", line 22, in construct                        │
│    19             path.become(previous_path)                                 │
│    20         path.add_updater(update_path)                                  │
│    21         self.add(path, dot)                                            │
│  ❱ 22         self.play(Rotating(dot, radians=PI, about_point=RIGHT, run_time│
│    23         self.wait()                                                    │
│    24         self.play(dot.animate.shift(UP))                               │
│    25         self.play(dot.animate.shift(LEFT))                             │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/scene/scene.py", line│
│877, in play                                                                  │
│     874             return np.max([animation.run_time for animation in animat│
│     875                                                                      │
│     876     def play(self, *args, **kwargs):                                 │
│  ❱  877         self.renderer.play(self, *args, **kwargs)                    │
│     878                                                                      │
│     879     def wait(self, duration=DEFAULT_WAIT_TIME, stop_condition=None): │
│     880         self.play(Wait(run_time=duration, stop_condition=stop_conditi│
│ File "/Users/ryan/PycharmProjects/manim-community/manim/utils/caching.py",   │
│line 58, in wrapper                                                           │
│    55             "List of the first few animation hashes of the scene: %(h)s│
│    56             {"h": str(self.animations_hashes[:5])},                    │
│    57         )                                                              │
│  ❱ 58         func(self, scene, *args, **kwargs)                             │
│    59                                                                        │
│    60     return wrapper                                                     │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/renderer/cairo_render│
│er.py", line 46, in wrapper                                                   │
│     43     def wrapper(self, scene, *args, **kwargs):                        │
│     44         self.animation_start_time = time.time()                       │
│     45         self.file_writer.begin_animation(not self.skip_animations)    │
│  ❱  46         func(self, scene, *args, **kwargs)                            │
│     47         self.file_writer.end_animation(not self.skip_animations)      │
│     48         self.num_plays += 1                                           │
│     49                                                                       │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/renderer/opengl_rende│
│rer.py", line 382, in play                                                    │
│    379         # TODO: Handle data locking / unlocking.                      │
│    380         if scene.compile_animation_data(*args, **kwargs):             │
│    381             scene.begin_animations()                                  │
│  ❱ 382             scene.play_internal()                                     │
│    383                                                                       │
│    384     def clear_screen(self):                                           │
│    385         window_background_color = color_to_rgba(config["background_col│
│ File "/Users/ryan/PycharmProjects/manim-community/manim/scene/scene.py", line│
│979, in play_internal                                                         │
│     976             self.animations, self.duration                           │
│     977         )                                                            │
│     978         for t in self.time_progression:                              │
│  ❱  979             self.update_to_time(t)                                   │
│     980             if not skip_rendering and not self.skip_animation_preview│
│     981                 self.renderer.render(self, t, self.moving_mobjects)  │
│     982             if self.stop_condition is not None and self.stop_conditio│
│ File "/Users/ryan/PycharmProjects/manim-community/manim/scene/scene.py", line│
│1188, in update_to_time                                                       │
│    1185             animation.update_mobjects(dt)                            │
│    1186             alpha = t / animation.run_time                           │
│    1187             animation.interpolate(alpha)                             │
│  ❱ 1188         self.update_mobjects(dt)                                     │
│    1189         self.update_meshes(dt)                                       │
│    1190         self.update_self(dt)                                         │
│    1191                                                                      │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/scene/scene.py", line│
│322, in update_mobjects                                                       │
│     319             Change in time between updates. Defaults (mostly) to 1/fr│
│     320         """                                                          │
│     321         for mobject in self.mobjects:                                │
│  ❱  322             mobject.update(dt)                                       │
│     323                                                                      │
│     324     def update_meshes(self, dt):                                     │
│     325         for obj in self.meshes:                                      │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/mobject/mobject.py", │
│line 804, in update                                                           │
│     801             if "dt" in parameters:                                   │
│     802                 updater(self, dt)                                    │
│     803             else:                                                    │
│  ❱  804                 updater(self)                                        │
│     805         if recursive:                                                │
│     806             for submob in self.submobjects:                          │
│     807                 submob.update(dt, recursive)                         │
│ File "../scenes/playground.py", line 18, in update_path                      │
│    15         path.set_points_as_corners([dot.get_center(), dot.get_center()]│
│    16         def update_path(path):                                         │
│    17             previous_path = path.copy()                                │
│  ❱ 18             previous_path.add_points_as_corners([dot.get_center()])    │
│    19             path.become(previous_path)                                 │
│    20         path.add_updater(update_path)                                  │
│    21         self.add(path, dot)                                            │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/mobject/types/vectori│
│zed_mobject.py", line 737, in add_points_as_corners                           │
│     734                                                                      │
│     735     def add_points_as_corners(self, points: np.ndarray) -> "VMobject"│
│     736         for point in points:                                         │
│  ❱  737             self.add_line_to(point)                                  │
│     738         return points                                                │
│     739                                                                      │
│     740     def set_points_as_corners(self, points: Sequence[float]) -> "VMob│
│ File "/Users/ryan/PycharmProjects/manim-community/manim/mobject/types/vectori│
│zed_mobject.py", line 676, in add_line_to                                     │
│     673         self.add_cubic_bezier_curve_to(                              │
│     674             *[                                                       │
│     675                 interpolate(self.get_last_point(), point, a)         │
│  ❱  676                 for a in np.linspace(0, 1, nppcc)[1:]                │
│     677             ]                                                        │
│     678         )                                                            │
│     679         return self                                                  │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/mobject/types/vectori│
│zed_mobject.py", line 638, in add_cubic_bezier_curve_to                       │
│     635         anchor : np.ndarray                                          │
│     636             anchor                                                   │
│     637         """                                                          │
│  ❱  638         self.throw_error_if_no_points()                              │
│     639         new_points = [handle1, handle2, anchor]                      │
│     640         if self.has_new_path_started():                              │
│     641             self.append_points(new_points)                           │
│ File "/Users/ryan/PycharmProjects/manim-community/manim/mobject/mobject.py", │
│line 2663, in throw_error_if_no_points                                        │
│    2660     # Errors                                                         │
│    2661     def throw_error_if_no_points(self):                              │
│    2662         if config.renderer == "opengl":                              │
│  ❱ 2663             if len(self.data["points"]) == 0:                        │
│    2664                 caller_name = sys._getframe(1).f_code.co_name        │
│    2665                 raise Exception(                                     │
│    2666                     f"Cannot call Mobject.{caller_name} for a Mobject│
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'points'```

<!-- Insert screenshots here (only when absolutely necessary, we prefer copy/pasted output!) -->

</details>


## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
PASTE HERE
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:
<!-- output of `tlmgr list --only-installed` for TeX Live or a screenshot of the Packages page for MikTeX -->
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

## Additional comments
<!-- Add further context that you think might be relevant for this issue here. -->

**Comment by PhotonSpheres** [comment]
Remark: This code works if one changes `path = VMobject()` to `path = OpenGLVMobject()`, since the error comes from calling the a function in the original mobject module.

**Comment by ryanmccauley211** [comment]
> Remark: This code works if one changes `path = VMobject()` to `path = OpenGLVMobject()`, since the error comes from calling a method in the original mobject module.

Ah yes makes sense, I forgot that directly calling VMObject won't trigger the opengl compatibility that switches the bases
