### ISSUE TITLE
M1 Mac, Manim not running properly

### ISSUE THREAD

**Issue by PxlRift** [ManimCommunity/manim#2289]
I have installed all of the dependencies as per the official documentation, but when I run 'manim' in the terminal I get the following error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim/__init__.py", line 34, in <module>
    from .animation.animation import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim/animation/animation.py", line 5, in <module>
    from ..mobject import mobject, opengl_mobject
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim/mobject/mobject.py", line 36, in <module>
    from ..utils.color import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim/utils/color.py", line 28, in <module>
    from ..utils.bezier import interpolate
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/manim/utils/bezier.py", line 25, in <module>
    from scipy import linalg
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scipy/__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scipy/_lib/_ccallback.py", line 1, in /<module>'
    from . import _ccallback_c
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scipy/_lib/_ccallback_c.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/scipy/_lib/_ccallback_c.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/_ccallback_c.cpython-310-darwin.so' (no such file)

<img width="1434" alt="Screen Shot 2021-11-12 at 4 53 12 pm" src="https://user-images.githubusercontent.com/56781157/141420203-4353583b-1ad9-4330-97b8-1455ea93d5ce.png">

**Comment by hydrobeam** [comment]
Hello! This most likely seems to be an issue due to the fact you're on Python 3.10, and some of our dependencies aren't yet working with 3.10. Try downgrading to Python 3.9 instead.

**Comment by Darylgolden** [comment]
Manim should work on Python 3.10 now.
