### ISSUE TITLE
Manim throws "'Angle' is not defined"

### ISSUE THREAD

**Issue by Roopesh2** [ManimCommunity/manim#2339]
## Description of bug / unexpected behavior
I was creating a drawing of sins and cosines It uses Angle class to draw angle between two lines. But when running manim command, it says that Angle class is not defined. I checked changelogs to check whether Angle class has depreciated or not.
It worked well a year ago with older version of Manim (v0.7.0). Even I generated a image : ![Sin_And_Cos_ManimCE_v0 7 0](https://user-images.githubusercontent.com/62459820/143770122-16cdc898-e39b-4136-83a6-d0f2658e0650.png)

## Expected behavior
Everything should work and a image must be generated.

## How to reproduce the issue
 Install manim v0.12.0 via scoop
 create a file (with name main.py) and add following code:
<details>

```py

from manim import *
from math import *
import numpy as np

SHIFT  = np.array([-1.5, -2, 0])
ang    = PI/4
circle = Circle(radius=5, color=None).set_stroke(GRAY, opacity=0.5)
dot    = Dot(point=circle.point_from_proportion(ang/TAU))
dot_center= dot.get_center()

def basis (u_brace=True, u_brace_ang=PI/2):
  axes = Axes(tips=False, axis_config={
      "include_ticks": False
  }, x_length=100, y_length=100)
   
  g = Group(
    axes,
    circle,
    theta(),
    get_unit_line(u_brace, u_brace_ang),
    dot,
  )
  return g.shift(SHIFT)
def theta ():
  th = Angle(
    line1=Line(start=ORIGIN, end=np.array([1, 0, 0])),
    line2=Line(start=ORIGIN, end=dot_center),
  )
  theta_text = MathTex("\\theta").next_to(ORIGIN, np.array([2, 0.5, 0.0]))

  return Group(th, theta_text)
def sin_cos ():
  sin_line = Line(
    start=dot_center,
    end=np.array([dot_center[0], 0, 0])
  )
  cos_line = Line(
    start=ORIGIN,
    end=np.array([dot_center[0], 0, 0])
  )
  cos_brace = Brace(cos_line)
  cos_brace_text = cos_brace.get_tex("cos(\\theta)", buff=0.08)
  
  _sin = Group(
    sin_line,
    rotated_brace(sin_line, "sin(\\theta)", PI/2, -0.3, PI/2)
  ).set_color(GREEN_C)

  _cos = Group(
    cos_line,
    cos_brace,
    cos_brace_text
  ).set_color(YELLOW_C)

  return Group(_sin, _cos).shift(SHIFT)

class Sin_And_Cos (Scene):
  def construct(self):
    self.add(basis(), sin_cos())

```
</details>

Then run "manim -ps main.py Sin_And_Cos"

## Logs
<details><summary>Terminal output</summary>

```
C:\Projects\Manim Projects\All Trig Functions>manim -ps main.py Sin_And_Cos



Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\manim\__main__.py", line 75, in main
    scene.render()
  File "c:\program files\python37\lib\site-packages\manim\scene\scene.py", line 88, in render
    self.construct()
  File "main.py", line 59, in construct
    self.add(basis(), sin_cos())
  File "main.py", line 19, in basis
    theta(),
  File "main.py", line 25, in theta
    th = Angle(
NameError: name 'Angle' is not defined
```
</details>

## System specifications

<details><summary>System Details</summary>

- OS: windows 10.0.19043
- RAM: 4GB
- Python version (`python/py/python3 --version`): 3.7.0
- Installed modules (provide output from `pip list`):
```
Package                       Version
----------------------------- ------------
alabaster                     0.7.12
altgraph                      0.17
appdirs                       1.4.4
astroid                       2.6.2
atomicwrites                  1.4.0
attrs                         21.2.0
Babel                         2.9.1
beautifulsoup4                4.9.3
black                         20.8b1
bleach                        3.2.1
cachetools                    4.1.1
cairocffi                     1.2.0
certifi                       2020.11.8
cffi                          1.14.5
cfgv                          3.3.0
chardet                       3.0.4
click                         8.0.1
click-default-group           1.2.2
cloup                         0.7.1
colorama                      0.4.4
colour                        0.1.5
commonmark                    0.9.1
coverage                      5.5
cycler                        0.10.0
decorator                     5.0.9
Deprecated                    1.2.12
distlib                       0.3.2
docutils                      0.17.1
execnet                       1.9.0
filelock                      3.0.12
flake8                        3.9.2
furo                          2021.6.18b36
future                        0.18.2
gitdb                         4.0.7
GitPython                     3.1.18
glcontext                     2.3.4
google-closure-compiler-api   0.1.5
grpcio                        1.33.2
grpcio-tools                  1.33.2
identify                      2.2.10
idna                          2.10
imagesize                     1.2.0
importlib-metadata            3.10.1
iniconfig                     1.1.1
isort                         5.9.1
Jinja2                        3.0.1
keyring                       21.5.0
kiwisolver                    1.3.1
lazy-object-proxy             1.6.0
manim                         0.1.0
manim-ext                     0.0.1
manimce                       0.1.0
manimlib                      0.1.11
ManimPango                    0.3.0
mapbox-earcut                 0.12.10
MarkupSafe                    2.0.1
matplotlib                    3.4.2
mccabe                        0.6.1
moderngl                      5.6.4
moderngl-window               2.4.0
multipledispatch              0.6.0
mypy-extensions               0.4.3
networkx                      2.5
nodeenv                       1.6.0
numpy                         1.21.0
opencv-python                 4.3.0.36
packaging                     20.9
pangocairocffi                0.3.2
pangocffi                     0.6.0
parsimonious                  0.7.0
pathspec                      0.8.1
pathtools                     0.1.2
pefile                        2019.4.18
Pillow                        8.2.0
pip                           21.1.2
pkginfo                       1.6.1
pluggy                        0.13.1
pre-commit                    2.13.0
progressbar                   2.5
protobuf                      3.13.0
psutil                        5.8.0
py                            1.10.0
py2exe                        0.9.3.2
pycairo                       1.20.1
pycodestyle                   2.7.0
pycparser                     2.20
pydub                         0.25.1
pyflakes                      2.3.1
PyGithub                      1.55
pyglet                        1.5.18
Pygments                      2.9.0
pyinstaller                   4.0
pyinstaller-hooks-contrib     2020.10
PyJWT                         2.1.0
pylint                        2.9.3
PyNaCl                        1.4.0
pyparsing                     2.4.7
PyQt5                         5.15.1
PyQt5-sip                     12.8.1
pyreadline                    2.1
pyrr                          0.10.3
pytest                        6.2.4
pytest-cov                    2.12.1
pytest-forked                 1.3.0
pytest-xdist                  2.3.0
python-dateutil               2.8.1
pytz                          2021.1
pywin32                       228
pywin32-ctypes                0.2.0
PyYAML                        5.4.1
readme-renderer               28.0
recommonmark                  0.7.1
regex                         2021.7.1
requests                      2.15.1
requests-toolbelt             0.9.1
rfc3986                       1.4.0
rich                          10.4.0
rope                          0.17.0
schedule                      0.6.0
scipy                         1.6.1
screeninfo                    0.6.7
setuptools                    50.3.2
six                           1.16.0
smmap                         4.0.0
snowballstemmer               2.1.0
soupsieve                     2.2.1
Sphinx                        3.5.3
sphinx-copybutton             0.3.3
sphinx-js                     3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sphinxext-opengraph           0.4.2
toml                          0.10.2
tqdm                          4.61.1
twine                         3.2.0
typed-ast                     1.4.3
typing-extensions             3.10.0.0
UNKNOWN                       0.0.0
urllib3                       1.26.1
virtualenv                    20.4.7
watchdog                      2.1.3
webencodings                  0.5.1
wheel                         0.35.1
wincertstore                  0.2
wrapt                         1.12.1
zipp                          3.4.1
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution : MikTex
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version git-2020-03-30-8d019db Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.1 (GCC) 20200328
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
libavutil      56. 42.102 / 56. 42.102
libavcodec     58. 77.101 / 58. 77.101
libavformat    58. 42.100 / 58. 42.100
libavdevice    58.  9.103 / 58.  9.103
libavfilter     7. 77.101 /  7. 77.101
libswscale      5.  6.101 /  5.  6.101
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100
```
</details>

## Additional comments
I checked my python 3.7.0 geometry.py file and surprisingly IT DIDN'T CONTAINED ANGLE CLASS:
![image](https://user-images.githubusercontent.com/62459820/143770841-3f1aa95c-9786-41da-97a7-9eec0c8c35e8.png)

**Comment by behackl** [comment]
Your pip output mentions

```
manim                         0.1.0
```

which is ancient. You will need to upgrade to a more recent version.

**Comment by Roopesh2** [comment]
@behackl how is that possible? I started using this after 0.5.0

**Comment by Roopesh2** [comment]
I tried `python -m manim`. This is what is it gives
![image](https://user-images.githubusercontent.com/62459820/143792174-cc0aa06b-5b01-4440-a882-2423203ee718.png)

**Comment by Darylgolden** [comment]
That means you have two or more Pythons installed on your computer, and the Manim that's used when you type `manim` is an outdated one, while the one that's used when you type `python -m manim` is the updated one.

**Comment by Roopesh2** [comment]
Oh yes I was running `py` command to render which has outdated version 😖. @Darylgolden I have two python versions installed (3.7 & 3.8). I removed both `manim` &  `manimce` from both versions and installed `manim` again. And that solved issue😅.
