### ISSUE TITLE
Installation 'successful', but manim fails to launch

### ISSUE THREAD

**Issue by MikiVanousek** [ManimCommunity/manim#2632]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [troubleshooting page](https://docs.manim.community/en/stable/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

I managed to successfully `pip3 install manim`, but when I run `manim --help` (`manim` anything), I get the following error.

## Installation logs

<details><summary>Terminal output</summary>

```
Traceback (most recent call last):
  File "/home/miki/prg/manim2/.venv/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/manim/__init__.py", line 36, in <module>
    from .animation.animation import *
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/manim/animation/animation.py", line 6, in <module>
    from manim.mobject.opengl.opengl_mobject import OpenGLMobject
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/manim/mobject/opengl/opengl_mobject.py", line 17, in <module>
    from manim.utils.bezier import integer_interpolate, interpolate
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/manim/utils/bezier.py", line 27, in <module>
    from scipy import linalg
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 210, in <module>
    from ._matfuncs import *
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/scipy/linalg/_matfuncs.py", line 21, in <module>
    from ._matfuncs_sqrtm import sqrtm
  File "/home/miki/prg/manim2/.venv/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 24, in <module>
    from ._matfuncs_sqrtm_triu import within_block_loop
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): NixOS 22.05
- RAM: 16gb
- Python version (`python/py/python3 --version`): Python 3.9.10
- Installed modules (provide output from `pip list`):
```
Package                   Version
------------------------- -----------
backports.cached-property 1.0.1
certifi                   2021.10.8
charset-normalizer        2.0.12
click                     8.0.4
click-default-group       1.2.2
cloup                     0.7.1
colour                    0.1.5
commonmark                0.9.1
Cython                    0.29.24
decorator                 5.1.1
glcontext                 2.3.5
idna                      3.3
isosurfaces               0.1.0
manim                     0.15.1
ManimPango                0.4.0.post2
mapbox-earcut             0.12.11
moderngl                  5.6.4
moderngl-window           2.4.1
multipledispatch          0.6.0
networkx                  2.7.1
numpy                     1.22.3
Pillow                    9.0.1
pip                       21.2.4
pycairo                   1.20.1
pydub                     0.25.1
pyglet                    1.5.23
Pygments                  2.11.2
pyrr                      0.10.3
requests                  2.27.1
rich                      12.0.0
scipy                     1.8.0
screeninfo                0.8
setuptools                58.1.0
six                       1.16.0
skia-pathops              0.7.2
srt                       3.5.2
tqdm                      4.63.0
urllib3                   1.26.9
watchdog                  2.1.6
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/home/miki/prg/manim2/.venv/bin/python -m pip install --upgrade pip' command.
```
</details>

<details><summary>LaTeX details</summary>
I did not install latex yet
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.3.0 (GCC)
configuration: --disable-static --prefix=/nix/store/vhvmvwkfy7hx1nlhrvjaf45x159vn3x6-ffmpeg-4.4.1 --arch=x86_64 --target_os=linux --enable-gpl --enable-version3 --enable-shared --enable-pic --enable-libsrt --enable-runtime-cpudetect --enable-hardcoded-tables --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --disable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --disable-doc --enable-libass --enable-bzlib --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libmp3lame --enable-iconv --enable-libtheora --enable-libssh --enable-vaapi --enable-libdrm --enable-vdpau --enable-libvorbis --enable-libvpx --enable-lzma --disable-opengl --disable-libmfx --disable-libaom --enable-libpulse --enable-sdl2 --enable-libsoxr --enable-libx264 --enable-libxvid --enable-libzimg --enable-zlib --enable-libopus --enable-libspeex --enable-libx265 --enable-libdav1d --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```
</details>

**Comment by Darylgolden** [comment]
Does using a function from scipy's linear algebra package work for you?

**Comment by naveen521kk** [comment]
`libstdc++.so.6` is something that should be present in your system. Search for that file in your package manager, and install it.

**Comment by MikiVanousek** [comment]
I did not manage to resolve it. I was thinking it might be caused by the recent move to OpenGL. But as I use a non-standard Linux distro NixOS, this will probably be the root of the issue.

**Comment by behackl** [comment]
> I did not manage to resolve it. I was thinking it might be caused by the recent move to OpenGL. But as I use a non-standard Linux distro NixOS, this will probably be the root of the issue.

The problem actually is not with manim itself, but one of its dependencies, `scipy` in this case. There are reports about other people having the same problem, take a look at e.g. https://discourse.nixos.org/t/nixos-with-poetry-installed-pandas-libstdc-so-6-cannot-open-shared-object-file/8442 -- maybe that helps!
