### ISSUE TITLE
Logger Problem: missing argument 'show_time' when running a scene

### ISSUE THREAD

**Issue by kolibril13** [ManimCommunity/manim#280]
When running this script in the current version of manim, 
```python
from manim import *

class Test(Scene):
    def construct(self):
        dot = Dot()
        self.add(dot)
        self.wait(1)

from pathlib import Path
if __name__ == "__main__":
    script = f"{Path(__file__).resolve()}"
    os.system(f"manim  -p -s  " + script )
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/jan-hendrik/projects/manim-community/example_scenes/basic.py", line 1, in <module>
    from manim import *
  File "/home/jan-hendrik/projects/manim-community/manim/__init__.py", line 4, in <module>
    from .config import config
  File "/home/jan-hendrik/projects/manim-community/manim/config.py", line 15, in <module>
    from .logger import logger
  File "/home/jan-hendrik/projects/manim-community/manim/logger.py", line 88, in <module>
    handlers=[RichHandler(console=console, show_time=themedict["log.timestamps"])],
TypeError: __init__() got an unexpected keyword argument 'show_time'

Process finished with exit code 1
```

**Comment by Aathish04** [comment]
What version of `rich` are you using @kolibril13 ?

It needs to be a version more recent than `4.2.1`. I recommend the most recent version.

**Comment by kolibril13** [comment]
```
> pip freeze | grep rich
rich==1.3.1
```
Thanks a lot, I updated it and now it is working again! :)
