### ISSUE TITLE
Fail to change resolution from render arguments

### ISSUE THREAD

**Issue by ponmike92** [ManimCommunity/manim#282]
macOS Catalina, I installed manim as package
fails when I try to change resolution settings 

`manim basic.py SquareToCircle -plr 700,700`

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manim/__init__.py", line 4, in <module>
    from .config import config
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manim/config.py", line 97, in <module>
    config = _parse_config(config_parser, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/manim/config.py", line 46, in _parse_config
    config["camera_config"].update({"pixel_height": height, "pixel_width": width})
KeyError: 'camera_config'
```

**Comment by leotrs** [comment]
@ponmike92 thank you for reporting this issue. We have been working on fixing it since you first reported it, I just forgot to post something here!

@Aathish04 I think this has been fixed, no? Or are we waiting on #283?

**Comment by Aathish04** [comment]
I wanted a concrete decision on #283 before I began removing stuff left right and center, but I'll try and see if i can fix this.

Also doesn't help that I've got exams next week soo... if anyone else wants to take this up that's fine by me. (tell me, so I don't work on this)

**Comment by leotrs** [comment]
@ponmike92 apologies for the delay. This has now been fixed in the latest master. Please try again and let us know if the error persists!
