### ISSUE TITLE
Cloup Distribution Not Found 

### ISSUE THREAD

**Issue by david-choi01** [ManimCommunity/manim#2941]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [troubleshooting page](https://docs.manim.community/en/stable/installation/troubleshooting.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

I installed Manim on my laptop running Arch Linux using the AUR package listed on the installation page. Afterwards, I tried to create a simple scene but got the following error:
`pkg_resources.DistributionNotFound: The 'cloup<0.14.0,>=0.13.0' distribution was not found and is required by manim
`

I looked for similar issues on the AUR package page, troubleshooting page, and the GitHub issues page but I couldn't find anything. 

## Installation logs

<details><summary></summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cloup 1.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('cloup<0.14.0,>=0.13.0'), {'manim'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/manim", line 33, in <module>
    sys.exit(load_entry_point('manim==0.16.0.post0', 'console_scripts', 'manim')())
  File "/usr/bin/manim", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/manim/__init__.py", line 6, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cloup<0.14.0,>=0.13.0' distribution was not found and is required by manim

```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Arch Linux
- RAM: 32GB
- Python version (`python/py/python3 --version`): Python 3.10.6
- Installed modules (provide output from `pip list`):
```
anytree                   2.8.0
apipkg                    3.0.1
appdirs                   1.4.4
apsw                      3.38.5.post1
argh                      0.26.2
asciidoc                  10.2.0
attrs                     22.1.0
autocommand               2.2.1
backports.cached-property 1.0.2
bcrypt                    3.2.2
beautifulsoup4            4.11.1
beets                     1.6.0
Brotli                    1.0.9
brotlicffi                1.0.9.2
btrfsutil                 5.19
build                     0.8.0
CacheControl              0.12.11
cachetools                5.2.0
cachy                     0.3.0
cchardet                  2.1.7
certifi                   2022.6.15
cffi                      1.15.1
chardet                   5.0.0
cleo                      1.0.0a5
click                     8.1.3
click-default-group       1.2.2
cloup                     1.0.0
colorama                  0.4.5
colour                    0.1.5
commonmark                0.9.1
confuse                   2.0.0
crashtest                 0.4.0
cryptography              37.0.4
css-parser                1.0.7
cssselect                 1.1.0
cupshelpers               1.0
cycler                    0.11.0
Cython                    0.29.32
decorator                 5.1.1
distlib                   0.3.6
distro                    1.7.0
dnspython                 2.2.1
docutils                  0.19
dulwich                   0.20.45
entrypoints               0.4
exceptiongroup            1.0.0rc9
feedparser                6.0.10
filelock                  3.8.0
fonttools                 4.37.1
future                    0.18.2
glcontext                 2.3.6
google-api-core           2.8.2
google-auth               1.35.0
googleapis-common-protos  1.56.3
html2text                 2020.1.16
html5-parser              0.4.10
html5lib                  1.1
hypothesis                6.54.4
idna                      3.3
ifaddr                    0.2.0
importlib-metadata        4.8.2
inflate64                 0.1.3
inflect                   6.0.0
iniconfig                 1.1.1
installer                 0.5.1
isosurfaces               0.1.0
jaraco.context            4.1.2
jaraco.functools          3.5.1
jaraco.text               3.9.1
jarowinkler               1.2.0
jeepney                   0.8.0
jellyfish                 0.9.1
Jinja2                    3.1.2
jsonschema                4.15.0
keyring                   23.4.0
kiwisolver                1.4.4
lark                      1.1.2
lensfun                   0.3.3
Levenshtein               0.20.1
libfdt                    1.6.1
libtorrent                2.0.7
libvirt-python            8.6.0
lockfile                  0.12.2
louis                     3.22.0
lxml                      4.9.1
manim                     0.16.0.post0
ManimPango                0.4.1
mapbox-earcut             1.0.0
Markdown                  3.4.1
MarkupSafe                2.1.1
matplotlib                3.5.2
mechanize                 0.4.8
mediafile                 0.9.0
meson                     0.63.1
moderngl                  5.7.0
moderngl-window           2.4.1
more-itertools            8.13.0
msgpack                   1.0.3
multipledispatch          0.6.0
multivolumefile           0.2.3
munkres                   1.1.4
musicbrainzngs            0.7.1
mutagen                   1.45.1
netifaces                 0.11.0
networkx                  2.8.6
nftables                  0.1
nspektr                   0.4.0
numpy                     1.23.2
optimus-manager           1.4
ordered-set               4.1.0
packaging                 21.3
pandas                    1.4.3
pathtools                 0.1.2
pdftotext                 2.2.2
pep517                    0.13.0
pexpect                   4.8.0
Pillow                    9.2.0
pip                       22.2.2
pkginfo                   1.8.3
platformdirs              2.5.2
pluggy                    1.0.0
ply                       3.11
poetry                    1.2.0
poetry-core               1.1.0
poetry-plugin-export      1.0.6
protobuf                  4.21.5
proton-client             0.7.1
protonvpn-cli             3.12.0
protonvpn-gui             1.10.0
protonvpn-nm-lib          3.12.0
psutil                    5.9.1
ptyprocess                0.7.0
py                        1.11.0
py7zr                     0.19.0
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pybcj                     1.0.1
pybind11                  2.10.0
pycairo                   1.21.0
pychm                     0.8.6
pycparser                 2.21
pycryptodome              3.15.0
pycryptodomex             3.12.0
pycups                    2.0.1
pycurl                    7.45.1
pydantic                  1.9.2
pydub                     0.25.1
pyglet                    1.5.26
Pygments                  2.13.0
PyGObject                 3.42.2
pyinotify                 0.9.6
pylev                     1.4.0
pyOpenSSL                 22.0.0
pyparsing                 3.0.9
pyppmd                    0.18.3
PyQt5                     5.15.7
PyQt5-sip                 12.11.0
PyQt6                     6.3.1
PyQt6-sip                 13.4.0
PyQt6-WebEngine           6.3.1
PyQtWebEngine             5.15.6
pyrr                      0.10.3
pyrsistent                0.18.1
pytest                    7.1.3
python-dateutil           2.8.2
python-distutils-extra    2.39
python-gnupg              0.5.0
pythondialog              3.5.3
pytz                      2022.1
pyxdg                     0.28
PyYAML                    6.0
pyzstd                    0.15.3
rapidfuzz                 2.4.2
reflink                   0.2.1
regex                     2022.6.2
requests                  2.28.1
requests-toolbelt         0.9.1
rich                      12.5.0
rsa                       4.9
scipy                     1.9.1
screeninfo                0.8
SecretStorage             3.3.3
selinux                   3.4
setuptools                62.3.1
setuptools-scm            7.0.5
sgmllib3k                 1.0.0
shellingham               1.5.0
six                       1.16.0
skia-pathops              0.7.2
sortedcontainers          2.4.0
soupsieve                 2.3.2.post1
srt                       3.5.2
systemd-python            234
team                      1.0
texttable                 1.6.4
tomli                     2.0.1
tomlkit                   0.11.4
tqdm                      4.64.1
trove-classifiers         2022.8.24
typing_extensions         4.3.0
ulauncher                 5.14.7
Unidecode                 1.3.4
unrardll                  0.1.5
urllib3                   1.26.12
validate-pyproject        0.9
virtualenv                20.13.0
watchdog                  2.1.10
webencodings              0.5.1
websocket-client          1.4.0
wheel                     0.37.1
yt-dlp                    2022.8.19
zeroconf                  0.38.7
zipp                      3.8.1
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): 
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version n5.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.1.1 (GCC) 20220730
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100

```
</details>

**Comment by naveen521kk** [comment]
Report it to the AUR maintainer, it looks like a packaging issue.

cc @Groctel

**Comment by Groctel** [comment]
On my way to fix it. You'll get an update when it's done. On future issues please use the AUR package comments. That way I can get an email and do it right away.

**Comment by Groctel** [comment]
Forgot to say: Issue was resolved, you can close it :)

**Comment by naveen521kk** [comment]
Thanks!
