### ISSUE TITLE
Error while installing on M1 MacBook

### ISSUE THREAD

**Issue by dahlgrenm** [ManimCommunity/manim#2998]
## Description of bug / unexpected behavior

While trying to install Manim to my device using the [MacOs Installation instructions](https://docs.manim.community/en/stable/installation/macos.html#macos) I encountered an error while trying to run the program.

## Expected behavior

Install Manim and run with version flag.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
$ pip3 uninstall manim
$ pip3 install manim
$ python3.9 -m manim --version
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
 $ python3.9 -m manim --version
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/manimpango/__init__.py", line 14, in <module>
    from .cmanimpango import *  # noqa: F403,F401
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cmanimpango.cpython-39-darwin.so' (no such file), '/usr/lib/cmanimpango.cpython-39-darwin.so' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/lib/python3.9/site-packages/manim/__init__.py", line 76, in <module>
    from .mobject.table import *
  File "/opt/homebrew/lib/python3.9/site-packages/manim/mobject/table.py", line 77, in <module>
    from manim.mobject.text.text_mobject import Paragraph
  File "/opt/homebrew/lib/python3.9/site-packages/manim/mobject/text/text_mobject.py", line 64, in <module>
    import manimpango
  File "/opt/homebrew/lib/python3.9/site-packages/manimpango/__init__.py", line 35, in <module>
    raise ImportError(msg)
ImportError: 

ManimPango could not import and load the necessary shared libraries.
This error may occur when ManimPango and its dependencies are improperly set up.
Please make sure the following versions are what you expect:

    * ManimPango v0.4.1, Python v3.9.15

If you believe there is a greater problem,
feel free to contact us or create an issue on GitHub:

    * Discord: https://www.manim.community/discord/
    * GitHub: https://github.com/ManimCommunity/ManimPango/issues

Original error: dlopen(/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cmanimpango.cpython-39-darwin.so' (no such file), '/usr/lib/cmanimpango.cpython-39-darwin.so' (no such file)
```

```
% pip3 install manimpango          
Requirement already satisfied: manimpango in /opt/homebrew/lib/python3.9/site-packages (0.4.1)

% python3.9 -m manimpango --version
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/manimpango/__init__.py", line 14, in <module>
    from .cmanimpango import *  # noqa: F403,F401
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cmanimpango.cpython-39-darwin.so' (no such file), '/usr/lib/cmanimpango.cpython-39-darwin.so' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/lib/python3.9/site-packages/manimpango/__init__.py", line 35, in <module>
    raise ImportError(msg)
ImportError: 

ManimPango could not import and load the necessary shared libraries.
This error may occur when ManimPango and its dependencies are improperly set up.
Please make sure the following versions are what you expect:

    * ManimPango v0.4.1, Python v3.9.15

If you believe there is a greater problem,
feel free to contact us or create an issue on GitHub:

    * Discord: https://www.manim.community/discord/
    * GitHub: https://github.com/ManimCommunity/ManimPango/issues

Original error: dlopen(/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cmanimpango.cpython-39-darwin.so' (no such file), '/usr/lib/cmanimpango.cpython-39-darwin.so' (no such file)
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): macOS 12.1
- RAM: 16GB
- Python version (`python/py/python3 --version`): Python 3.9.15
- Installed modules (provide output from `pip list`): 
```
Package                Version
---------------------- ------------
certifi                2021.10.8
charset-normalizer     2.0.11
click                  8.0.3
click-default-group    1.2.2
clipboard              0.0.4
cloup                  0.13.1
colour                 0.1.5
commonmark             0.9.1
construct              2.10.67
Cython                 0.29.32
decorator              5.1.1
ecdsa                  0.17.0
glcontext              2.3.6
idna                   3.3
isosurfaces            0.1.0
libusb1                3.0.0
manim                  0.16.0.post0
ManimPango             0.4.1
mapbox-earcut          0.12.11
mnemonic               0.20
moderngl               5.6.4
moderngl-window        2.4.2
multipledispatch       0.6.0
networkx               2.8.7
numpy                  1.22.3
pandas                 1.4.2
Pillow                 9.2.0
pip                    22.3
pybind11               2.10.0
pycairo                1.21.0
pydub                  0.25.1
pyglet                 2.0b1
Pygments               2.13.0
pyobjc-core            8.5.1
pyobjc-framework-Cocoa 8.5.1
pyperclip              1.8.2
pyrr                   0.10.3
python-dateutil        2.8.2
pytz                   2022.1
requests               2.27.1
rich                   12.6.0
scipy                  1.9.2
screeninfo             0.8.1
setuptools             65.4.1
six                    1.16.0
skia-pathops           0.7.2
srt                    3.5.2
svgelements            1.8.4
tqdm                   4.64.1
trezor                 0.13.0
typing_extensions      4.0.1
urllib3                1.26.8
watchdog               2.1.9
wheel                  0.37.1
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 14.0.0 (clang-1400.0.29.102)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```
</details>

## Additional comments

I was attempting to build the project from source but that had the same problem so I tried installing over pip instead. I have managed to get it working in a Docker container but unsure of the best way to edit the source and rebuild while working in the container (probably due to unfamiliarity with Docker).

**Comment by behackl** [comment]
It looks like you installed some Python packages in homebrew from within a terminal that was in Rosetta mode (which thus, IIRC, installs the x86_64 versions of the packages instead of the required arm64 ones).

I'd suggest to (1) uninstall the related packages, in particular `manimpango`, check that you aren't in a terminal in Rosetta mode, and try to reinstall it.

**Comment by behackl** [comment]
Feel free to keep commenting here, but this is not a problem with Manim itself; just a mix of incompatible versions of libraries on your end -- I'm thus closing the issue.

**Comment by dahlgrenm** [comment]
Yes that sounds like what happened, thank you for the help!
