### ISSUE TITLE
Manim plugins command is giving traceback error!

### ISSUE THREAD

**Issue by 7Wdev** [ManimCommunity/manim#3266]
## Description of bug / unexpected behavior
I cant see installed manim plugins!

## Expected behavior
to see the list of plugins

## How to reproduce the issue
by typing: manim plugins -l

<details><summary>Code for reproducing the problem</summary>

```py
Paste your code here.
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
Traceback (most recent call last):
  File "c:\users\user1\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user1\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python39\Scripts\manim.exe\__main__.py", line 7, in <module>
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\manim\cli\plugins\commands.py", line 31, in plugins
    list_plugins()
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\manim\plugins\plugins_flags.py", line 28, in list_plugins
    plugins = get_plugins()
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\manim\plugins\plugins_flags.py", line 18, in get_plugins
    plugins = {
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\manim\plugins\plugins_flags.py", line 19, in <dictcomp>
    entry_point.name: entry_point.load()
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2461, in load
    return self.resolve()
  File "c:\users\user1\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'module'
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)):
- RAM:
- Python version (`python/py/python3 --version`):
- Installed modules (provide output from `pip list`):
```
Windows 11
20gb ram
py 3.9.2

Package                        Version
------------------------------ -------------------
absl-py                        0.12.0
altgraph                       0.17
appdirs                        1.4.4
argcomplete                    1.12.2
astunparse                     1.6.3
async-generator                1.10
attrs                          20.3.0
auto-py-to-exe                 2.8.0
azure-cognitiveservices-speech 1.29.0
black                          20.8b1
boto                           2.49.0
bottle                         0.12.19
bottle-websocket               0.2.9
cachetools                     4.2.1
certifi                        2020.12.5
cffi                           1.15.1
chanim                         1.3
chardet                        4.0.0
charset-normalizer             3.1.0
click                          8.1.3
click-default-group            1.2.2
cloup                          0.13.1
colorama                       0.4.4
colour                         0.1.5
comtypes                       1.1.9
crcmod                         1.7
cryptography                   3.4.7
cycler                         0.10.0
dataclasses                    0.6
decorator                      5.1.1
deepl                          1.15.0
Eel                            0.12.4
enum-compat                    0.0.3
et-xmlfile                     1.1.0
fasteners                      0.16
ffmpeg-python                  0.2.0
filelock                       3.12.2
flatbuffers                    1.12
fsspec                         2023.6.0
func-timeout                   4.3.5
future                         0.18.2
gast                           0.4.0
gcs-oauth2-boto-plugin         2.7
geneticalgorithm2              6.8.2
gevent                         21.1.2
gevent-websocket               0.10.1
glcontext                      2.3.7
google-apitools                0.5.31
google-auth                    1.28.1
google-auth-oauthlib           0.4.4
google-pasta                   0.2.0
google-reauth                  0.1.1
greenlet                       1.0.0
grpcio                         1.34.1
gsutil                         4.60
gTTS                           2.3.2
h11                            0.12.0
h5py                           3.1.0
httplib2                       0.19.1
huggingface-hub                0.15.1
idna                           2.10
isosurfaces                    0.1.0
Jinja2                         3.1.2
joblib                         1.2.0
keras-nightly                  2.5.0.dev2021032900
Keras-Preprocessing            1.1.2
keyboard                       0.13.5
kiwisolver                     1.3.1
kociemba-manim-rubikscube      0.0.1
llvmlite                       0.40.1
manim                          0.17.3
manim-automata                 0.2.14
manim-cad-drawing-utils        0.0.4
manim-chemistry                0.1.0
manim-code-blocks              1.0.13
manim-data-structures          0.1.7
manim-fontawesome              6.3.0
manim-fonts                    0.2.0
manim-gearbox                  0.2.4
manim-ml                       0.0.24
manim-mobject-svg              0.2.0
manim-physics                  0.3.0
manim-rubikscube               0.1.0
manim-sequence-diagram         0.1.0
manim-svg-animations           0.3.13
manim-tikz                     0.0.1a1
manim-voiceover                0.3.3.post0
ManimPango                     0.4.3
mapbox-earcut                  1.0.1
Markdown                       3.3.4
markdown-it-py                 3.0.0
MarkupSafe                     2.1.3
matplotlib                     3.4.1
mdurl                          0.1.2
mediapipe                      0.8.3.1
mock                           2.0.0
moderngl                       5.8.2
moderngl-window                2.4.4
monotonic                      1.5
more-itertools                 9.1.0
MouseInfo                      0.1.3
mpmath                         1.3.0
msvc-runtime                   14.28.29910
multipledispatch               0.6.0
mutagen                        1.46.0
mypy-extensions                0.4.3
networkx                       2.8.8
numba                          0.57.1
numpy                          1.24.3
oauth2client                   4.1.3
oauthlib                       3.1.0
openai-whisper                 20230314
opencv-python                  4.5.1.48
openpyxl                       3.0.9
OppOpPopInit                   2.0.0
opt-einsum                     3.3.0
outcome                        1.1.0
packaging                      23.1
pandas                         1.3.5
pathspec                       0.8.1
pbr                            5.5.1
pefile                         2019.4.18
Pillow                         9.4.0
pip                            23.1.2
protobuf                       3.15.8
psutil                         5.8.0
py2exe                         0.10.3.0
pyarmor                        6.6.2
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
PyAudio                        0.2.13
PyAutoGUI                      0.9.52
pycairo                        1.24.0
pycaw                          20181226
pycparser                      2.20
pycryptodome                   3.10.1
pycryptodomex                  3.10.1
pydub                          0.25.1
PyGetWindow                    0.0.9
pyglet                         2.0.8
Pygments                       2.15.1
pyinstaller                    4.2
pyinstaller-hooks-contrib      2021.1
PyMsgBox                       1.0.9
pymunk                         6.4.0
pynput                         1.7.6
pyOpenSSL                      20.0.1
pyparsing                      2.4.7
pyperclip                      1.8.2
pypiwin32                      223
PyRect                         0.1.4
pyrr                           0.10.3
PyScreeze                      0.1.26
python-dateutil                2.8.1
python-dotenv                  0.21.1
python-slugify                 8.0.1
pyttsx3                        2.90
PyTweening                     1.0.3
pytz                           2021.3
pyu2f                          0.1.5
pywin32                        300
pywin32-ctypes                 0.2.0
PyYAML                         6.0
regex                          2023.6.3
reportlab                      3.6.12
requests                       2.31.0
requests-oauthlib              1.3.0
retry-decorator                1.1.1
rich                           13.4.2
rsa                            4.7.2
safetensors                    0.3.1
scipy                          1.10.1
screeninfo                     0.8.1
selenium                       3.141.0
setuptools                     49.2.1
Shapely                        1.8.5.post1
six                            1.15.0
skia-pathops                   0.7.4
sniffio                        1.2.0
sortedcontainers               2.4.0
sox                            1.4.1
srt                            3.5.3
stable-ts                      2.6.4
svgelements                    1.9.5
svgpathtools                   1.6.1
svgwrite                       1.4.3
sympy                          1.12
tensorboard                    2.4.1
tensorboard-plugin-wit         1.8.0
tensorflow                     2.5.0rc0
termcolor                      1.1.0
text-unidecode                 1.3
tf-estimator-nightly           2.5.0.dev2021032501
tiktoken                       0.3.1
tk                             0.1.0
tokenize-all                   1.0.17
tokenizers                     0.13.3
toml                           0.10.2
torch                          2.0.1
torchaudio                     2.0.2
tqdm                           4.65.0
transformers                   4.30.2
trio                           0.19.0
trio-websocket                 0.9.2
typed-ast                      1.4.2
typing-extensions              3.7.4.3
urllib3                        1.26.4
watchdog                       2.3.1
Werkzeug                       1.0.1
wheel                          0.36.2
whichcraft                     0.6.1
wrapt                          1.12.1
wsproto                        1.0.0
xmltodict                      0.13.0
zope.event                     4.5.0
zope.interface                 5.3.0
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by uwezi** [comment]
The error/warning messages you posted on Discord are related to different Windows applications - this might affect the functionality on your system. There does not seem to be any general problem with the command:

```manim plugins -l```

![image](https://github.com/ManimCommunity/manim/assets/8582807/f04575e0-fe1d-43e3-bfa5-99b5b4acba29)

**Comment by 7Wdev** [comment]
Believe the warning message of clipchamp isn't what causes the issue, it is negligible and it doesn't usually appear, what appears when I type the plugins list command is only the traceback

**Comment by MrDiver** [comment]
Cannot confirm that theres an issue in the version of manim, please check your setup and try reinstalling to see if the problem persists
