### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by HenYu-Yo** [ManimCommunity/manim#3333]
I use MathTex output Chinese, and I have set up CTEX, but I use Tex it doesn't give an error
```py
class demo(Scene):
    def construct(self):
        t1 = MathTex("你好", tex_template=TexTemplateLibrary.ctex)
        self.play(Write(t1))
        self.wait()
```
Log:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\Math\Project\manim\Scripts\manim.exe\__main__.py", line 7, in <module>
  File "F:\Math\Project\manim\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\manim\cli\render\commands.py", line 111, in render
    for SceneClass in scene_classes_from_file(file):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\manim\utils\module_ops.py", line 129, in scene_classes_from_file
    module = get_module(file_path)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\manim\utils\module_ops.py", line 52, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Math\Project\video\隐形的兔子\main.py", line 68, in <module>
    demo().render()
  File "F:\Math\Project\manim\Lib\site-packages\manim\scene\scene.py", line 223, in render
    self.construct()
  File "F:\Math\Project\video\隐形的兔子\main.py", line 65, in construct
    t1 = MathTex("和", "\\A_0", tex_template=TexTemplateLibrary.ctex)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\manim\mobject\text\tex_mobject.py", line 295, in __init__
    raise compilation_error
  File "F:\Math\Project\manim\Lib\site-packages\manim\mobject\text\tex_mobject.py", line 274, in __init__
    super().__init__(
  File "F:\Math\Project\manim\Lib\site-packages\manim\mobject\text\tex_mobject.py", line 83, in __init__
    file_name = tex_to_svg_file(
                ^^^^^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\manim\utils\tex_file_writing.py", line 54, in tex_to_svg_file
    dvi_file = compile_tex(
               ^^^^^^^^^^^^
  File "F:\Math\Project\manim\Lib\site-packages\manim\utils\tex_file_writing.py", line 200, in compile_tex
    print_all_tex_errors(log_file, tex_compiler, tex_file)
  File "F:\Math\Project\manim\Lib\site-packages\manim\utils\tex_file_writing.py", line 267, in print_all_tex_errors
    tex = f.readlines()
          ^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 536: illegal multibyte sequence

**Comment by uwezi** [comment]
LaTeX in general does not allow for Chinese characters in plain math-mode. Include your Chinese characters in a `\text{}` or use `Tex()` when you are not using math equation elements at the same time and it will work. Also I would recommend to always use python's raw strings (`r"..."`) when dealing with LaTeX elements in Manim.

```python
class demo(Scene):
    def construct(self):
        t1 = MathTex(r"\text{你好}", tex_template=TexTemplateLibrary.ctex)
        self.play(Write(t1))
        t2 = Tex(r"你好", tex_template=TexTemplateLibrary.ctex)
        self.play(Write(t2).set_color(RED).next_to(t1,DOWN))
        self.wait()
```
![image](https://github.com/ManimCommunity/manim/assets/8582807/f90141a6-850e-4931-9cb9-d22983c11ab1)

**Comment by HenYu-Yo** [comment]
> LaTeX 通常不允许在普通数学模式下使用汉字。当您不同时使用数学方程式元素时，将您的汉字包含在 or 中使用，它将起作用。此外，我建议在处理Manim中的LaTeX元素时始终使用python的原始字符串（）。`\text{}``Tex()``r"..."`
> 
> ```python
> class demo(Scene):
>     def construct(self):
>         t1 = MathTex(r"\text{你好}", tex_template=TexTemplateLibrary.ctex)
>         self.play(Write(t1))
>         t2 = Tex(r"你好", tex_template=TexTemplateLibrary.ctex)
>         self.play(Write(t2).set_color(RED).next_to(t1,DOWN))
>         self.wait()
> ```
> 
> ![image](https://user-images.githubusercontent.com/8582807/261007167-f90141a6-850e-4931-9cb9-d22983c11ab1.png)

How do I set the font in text{}？

**Comment by uwezi** [comment]
Sorry I don't understand Chinese...

- `\text{}` is a LaTeX macro to be used within LaTeX's math mode, you cannot set a different font there easily (but it is possible)
- `Text()` is a Manim object where you can set the font, but it is not rendered in LaTeX
- `Tex()` is also a Manim object where you also could change the font

I suggest you come over to Discord where you will find a Chinese community as well, which might give you tips particularly related to Chinese text in Manim: 
[Where can I find more resources for learning Manim?](https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim)

**Comment by HenYu-Yo** [comment]
> 对不起，我不懂中文...
> 
> * `\text{}`是一个在 LaTeX 的数学模式下使用的 LaTeX 宏，您不能在那里轻松设置不同的字体（但这是可能的）
> * `Text()`是一个 Manim 对象，您可以在其中设置字体，但它不会在 LaTeX 中呈现
> * `Tex()`也是一个 Manim 对象，您也可以在其中更改字体
> 
> 我建议你来 Discord，在那里你也可以找到一个中文社区，这可能会给你一些提示，特别是与 Manim 中的中文文本相关的提示：[我在哪里可以找到更多学习 Manim 的资源？](https://docs.manim.community/en/stable/faq/general.html?highlight=discord#where-can-i-find-more-resources-for-learning-manim)

Thanks.
