### ISSUE TITLE
Issue installing Manim

### ISSUE THREAD

**Issue by aniura** [ManimCommunity/manim#3379]
#### Preliminaries

- [X ] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [X ] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error

Hi, after trying this 

pip3 install manim

I get the message Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_7z4fxkq/mapbox-earcut/

## Installation logs

<details><summary>Terminal output</summary>

pip3 install manim
Collecting manim
  Using cached https://files.pythonhosted.org/packages/5d/b3/405c04a0015b9548d807a387d6172179320238960ee00ab3e2ab0bafbcd1/manim-0.6.0-py3-none-any.whl
Collecting pycairo<2.0,>=1.19 (from manim)
  Using cached https://files.pythonhosted.org/packages/bc/3f/64e6e066d163fbcf13213f9eeda0fc83376243335ea46a66cefd70d62e8f/pycairo-1.20.1.tar.gz
Collecting decorator<5.0.0 (from manim)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting networkx<3.0,>=2.5 (from manim)
  Downloading https://files.pythonhosted.org/packages/f3/b7/c7f488101c0bb5e4178f3cde416004280fd40262433496830de8a8c21613/networkx-2.5.1-py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 484kB/s 
Collecting cloup<0.8.0,>=0.7.0 (from manim)
  Downloading https://files.pythonhosted.org/packages/4b/c5/0a47ad3613dc43a6a984efdadb85b3afbc6f4acff2e6dc5c05e3752d680b/cloup-0.7.1-py2.py3-none-any.whl
Collecting Pillow (from manim)
  Using cached https://files.pythonhosted.org/packages/7d/2a/2fc11b54e2742db06297f7fa7f420a0e3069fdcf0e4b57dfec33f0b08622/Pillow-8.4.0.tar.gz
Collecting numpy<2.0,>=1.9 (from manim)
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting watchdog (from manim)
  Using cached https://files.pythonhosted.org/packages/a5/17/a31fc6b90ff861a27debd0650bfbca17e074fdc3e037f392872fad76c726/watchdog-2.3.1.tar.gz
Collecting pydub (from manim)
  Using cached https://files.pythonhosted.org/packages/a6/53/d78dc063216e62fc55f6b2eebb447f6a4b0a59f55c8406376f76bf959b08/pydub-0.25.1-py2.py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from manim)
  Using cached https://files.pythonhosted.org/packages/a0/a1/b153a0a4caf7a7e3f15c2cd56c7702e2cf3d89b1b359d1f1c5e59d68f4ce/importlib_metadata-4.8.3-py3-none-any.whl
Collecting manimpango<0.3.0,>=0.2.4 (from manim)
  Downloading https://files.pythonhosted.org/packages/32/d8/3d4ac5747940bcc73798b49590b4e9ab3b91a17e594fcf0e0bfaf7c3da14/ManimPango-0.2.6.tar.gz (455kB)
    100% |████████████████████████████████| 460kB 666kB/s 
Collecting requests (from manim)
  Using cached https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl
Collecting scipy (from manim)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9MB)
    100% |████████████████████████████████| 25.9MB 72kB/s 
Collecting mapbox-earcut<0.13.0,>=0.12.10 (from manim)
  Using cached https://files.pythonhosted.org/packages/01/5c/35d5bc8fb1f6844e832466f3b56bce19a646493ccb7df66bec484bbc84b5/mapbox_earcut-0.12.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_7z4fxkq/mapbox-earcut/setup.py", line 4, in <module>
        from pybind11.setup_helpers import Pybind11Extension, build_ext
    ModuleNotFoundError: No module named 'pybind11'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_7z4fxkq/mapbox-earcut/

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Linux Mint 19.1
- RAM: 8103564 kB
- Python version (`python/py/python3 --version`): Python 3.7.4
- Installed modules (provide output from `pip list`):
```
Package                            Version
---------------------------------- ---------
adaptive                           0.15.1
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.3
appdirs                            1.4.4
asn1crypto                         1.0.1
astroid                            2.3.1
astropy                            3.2.2
atomicwrites                       1.3.0
attrs                              19.2.0
Babel                              2.7.0
backcall                           0.1.0
backports.functools-lru-cache      1.6.4
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
beautifulsoup4                     4.8.0
bitarray                           1.0.1
bkcharts                           0.2
bleach                             3.1.0
bokeh                              2.4.3
boto                               2.49.0
Bottleneck                         1.2.1
certifi                            2019.9.11
cffi                               1.12.3
chardet                            3.0.4
Click                              7.0
cloudpickle                        1.2.2
clyent                             1.2.2
colorama                           0.4.1
colorcet                           3.0.1
conda                              22.9.0
conda-build                        3.18.9
conda-package-handling             1.6.0
conda-verify                       3.4.2
construct                          2.10.68
contextlib2                        0.6.0
cryptography                       2.7
cycler                             0.10.0
Cython                             0.29.13
cytoolz                            0.10.0
dask                               2.5.2
decorator                          4.4.0
defusedxml                         0.6.0
distributed                        2.5.2
docutils                           0.15.2
entrypoints                        0.3
et-xmlfile                         1.0.1
ez-setup                           0.9
fastcache                          1.1.0
filelock                           3.0.12
Flask                              1.1.1
fonttools                          4.38.0
fsspec                             0.5.2
future                             0.18.3
gevent                             1.4.0
glcontext                          2.4.0
glob2                              0.7
gmpy2                              2.0.8
greenlet                           0.4.15
h5py                               2.9.0
HeapDict                           1.0.1
html5lib                           1.0.1
idna                               2.8
imageio                            2.6.0
imagesize                          1.1.0
importlib-metadata                 6.0.0
ipykernel                          5.1.2
ipympl                             0.9.3
ipython                            7.8.0
ipython_genutils                   0.2.0
ipywidgets                         7.5.1
ipywidgets-bokeh                   1.3.0
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.15.1
jeepney                            0.4.1
Jinja2                             2.10.3
joblib                             0.13.2
json5                              0.8.5
jsonschema                         3.0.2
jupyter                            1.0.0
jupyter-client                     5.3.3
jupyter-console                    6.0.0
jupyter-core                       4.5.0
jupyterlab                         1.1.4
jupyterlab-server                  1.0.6
k3d                                2.15.2
keyring                            18.0.0
kiwisolver                         1.1.0
lazy-object-proxy                  1.4.2
libarchive-c                       2.8
lief                               0.9.0
llvmlite                           0.29.0
locket                             0.2.0
loky                               3.3.0
lxml                               4.4.1
Markdown                           3.4.1
MarkupSafe                         1.1.1
matplotlib                         3.5.3
mccabe                             0.6.1
mergedeep                          1.3.4
mistune                            0.8.4
mkl-fft                            1.0.14
mkl-random                         1.1.0
mkl-service                        2.3.0
mock                               3.0.5
moderngl                           5.8.2
more-itertools                     7.2.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.6.0
nbformat                           4.4.0
networkx                           2.3
nltk                               3.4.5
nose                               1.3.7
notebook                           6.0.1
numba                              0.45.1
numexpr                            2.7.0
numpy                              1.21.6
numpyarray-to-latex                0.1.0
numpydoc                           0.9.1
olefile                            0.46
openpyxl                           3.0.0
packaging                          19.2
pandas                             0.25.1
pandocfilters                      1.4.2
panel                              0.14.4
param                              1.13.0
parso                              0.5.1
partd                              1.0.0
path.py                            12.0.1
pathlib2                           2.3.5
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.7.0
pickleshare                        0.7.5
Pillow                             6.2.0
pip                                23.2.1
pkginfo                            1.5.0.1
plotly                             5.13.1
pluggy                             0.13.0
ply                                3.11
prometheus-client                  0.7.1
prompt-toolkit                     2.0.10
psutil                             5.6.3
ptyprocess                         0.6.0
py                                 1.8.0
pybind11                           2.11.1
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pyct                               0.5.0
pycurl                             7.43.0.3
pyflakes                           2.1.1
pyftdi                             0.13.4
Pygments                           2.4.2
pylibftdi                          0.20.0
pylint                             2.4.2
pyodbc                             4.0.27
pyOpenSSL                          19.0.0
pyparsing                          2.4.2
pyrsistent                         0.15.4
pyserial                           3.5
PySocks                            1.7.1
pytest                             5.2.1
pytest-arraydiff                   0.3
pytest-astropy                     0.5.0
pytest-doctestplus                 0.4.0
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.0
pytz                               2019.3
pyusb                              1.2.1
pyviz-comms                        2.2.1
PyWavelets                         1.0.3
PyYAML                             5.1.2
pyzmq                              18.1.0
QtAwesome                          0.6.0
qtconsole                          4.5.5
QtPy                               1.9.0
requests                           2.22.0
rope                               0.14.0
ruamel_yaml                        0.15.46
sbp                                4.12.0
scikit-image                       0.15.0
scikit-learn                       0.21.3
scipy                              1.7.3
seaborn                            0.9.0
SecretStorage                      3.1.1
Send2Trash                         1.5.0
setuptools                         68.0.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.12.0
snowballstemmer                    2.0.0
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.9.3
Sphinx                             2.2.0
sphinxcontrib-applehelp            1.0.1
sphinxcontrib-devhelp              1.0.1
sphinxcontrib-htmlhelp             1.0.2
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.2
sphinxcontrib-serializinghtml      1.1.3
sphinxcontrib-websupport           1.1.2
spyder                             3.3.6
spyder-kernels                     0.5.2
SQLAlchemy                         1.3.9
statsmodels                        0.10.1
sympy                              1.10.1
sympy-plot-backends                1.6.7
tables                             3.5.2
tblib                              1.4.0
tenacity                           8.2.2
terminado                          0.8.2
testpath                           0.4.2
toolz                              0.10.0
tornado                            6.0.3
tqdm                               4.65.0
traitlets                          4.3.3
traittypes                         0.2.1
typing_extensions                  4.5.0
unicodecsv                         0.14.1
urllib3                            1.24.2
vtk                                9.0.1
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.16.0
wheel                              0.41.2
widgetsnbextension                 3.5.1
wrapt                              1.11.2
wurlitzer                          1.0.3
xlrd                               1.2.0
XlsxWriter                         1.2.1
xlwt                               1.3.0
zict                               1.0.0
zipp                               0.6.0

```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): TeX Live 2017
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
configuration: --prefix=/home/aniura/anaconda3 --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1566210161358/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

```
</details>

**Comment by aniura** [comment]
Sorry, I didn't know. Thanks!

**Comment by uwezi** [comment]
the information on the installation page should have been updated, so far it's only mentioned in the version history:
https://docs.manim.community/en/stable/changelog/0.17.0-changelog.html#breaking-changes
