### ISSUE TITLE
Manim installation not working with conda and python 3.12.3

### ISSUE THREAD

**Issue by HelixPiano** [ManimCommunity/manim#3731]
## Description of bug / unexpected behavior
Hello everyone,
I tried to install Manim via conda, but it failed due to dependencies. See logs for the error message. The environment is basically empty when starting the installation.  
Edit:  
I ran a clean install of miniconda and create a new environment (not applying any updates beforehand). The installation of manim now works. The resulting installation is in python 3.11.9 (manim environment) and not 3.12.2 (miniconda base environment).

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
conda install -c conda-forge manim
```

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

</details>

## Logs
<details><summary>Terminal output</summary>

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package manim-0.17.0-pyhd8ed1ab_0 requires watchdog >=2.1.6,<3.0.0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ manim is installable with the potential options
│  ├─ manim [0.15.2|0.16.0.post0] would require
│  │  └─ mapbox_earcut >=0.12.10,<0.13.0  with the potential options
│  │     ├─ mapbox_earcut 0.12.10 would require
│  │     │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  │     ├─ mapbox_earcut 0.12.10 would require
│  │     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  │     ├─ mapbox_earcut 0.12.10 would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │     └─ mapbox_earcut 0.12.10 would require
│  │        └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ manim [0.17.0|0.17.1|0.17.2|0.17.3] would require
│  │  └─ watchdog >=2.1.6,<3.0.0  with the potential options
│  │     ├─ watchdog [2.1.6|2.1.7|...|2.3.1] would require
│  │     │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  │     ├─ watchdog [2.1.0|2.1.1|...|2.1.6] would require
│  │     │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  │     ├─ watchdog [2.1.0|2.1.1|...|2.1.9] would require
│  │     │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  │     ├─ watchdog [2.1.0|2.1.1|...|2.3.1] would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │     ├─ watchdog [2.1.0|2.1.1|...|2.3.1] would require
│  │     │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  │     ├─ watchdog [2.1.9|2.2.0|2.2.1|2.3.0|2.3.1] would require
│  │     │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  │     └─ watchdog 2.1.6 conflicts with any installable versions previously reported;
│  └─ manim [0.18.0|0.18.0.post0] would require
│     └─ watchdog >=2.1,<3.0.0  with the potential options
│        ├─ watchdog [2.1.6|2.1.7|...|2.3.1], which can be installed (as previously explained);
│        ├─ watchdog [2.1.0|2.1.1|...|2.1.6], which can be installed (as previously explained);
│        ├─ watchdog [2.1.0|2.1.1|...|2.1.9], which can be installed (as previously explained);
│        ├─ watchdog [2.1.0|2.1.1|...|2.3.1], which can be installed (as previously explained);
│        ├─ watchdog [2.1.0|2.1.1|...|2.3.1], which can be installed (as previously explained);
│        ├─ watchdog [2.1.9|2.2.0|2.2.1|2.3.0|2.3.1], which can be installed (as previously explained);
│        ├─ watchdog 2.1.6 conflicts with any installable versions previously reported;
│        └─ watchdog [2.1.1|2.1.3] conflicts with any installable versions previously reported;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 10
- RAM: 16GB
- Python version (`python/py/python3 --version`): 3.12.3
- Installed modules (provide output from `pip list`):
```
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.45.3               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
python                    3.12.3          h2628c8c_0_cpython    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge

```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```

```
</details>

**Comment by cub525** [comment]
I also had a very similar error when attempting to install Manim with Python 3.12.5, but my dependency problem was with NumPy

**Comment by spacetime-labs** [comment]
Also get a problem with numpy:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/envManim/bin/manim", line 6, in <module>
    from manim.__main__ import main
  File "/opt/homebrew/Caskroom/miniconda/base/envs/envManim/lib/python3.12/site-packages/manim/__init__.py", line 13, in <module>
    from ._config import *
  File "/opt/homebrew/Caskroom/miniconda/base/envs/envManim/lib/python3.12/site-packages/manim/_config/__init__.py", line 12, in <module>
    from .utils import ManimConfig, ManimFrame, make_config_parser
  File "/opt/homebrew/Caskroom/miniconda/base/envs/envManim/lib/python3.12/site-packages/manim/_config/utils.py", line 27, in <module>
    import numpy as np
  File "/opt/homebrew/Caskroom/miniconda/base/envs/envManim/lib/python3.12/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
