### ISSUE TITLE
Manim

### ISSUE THREAD

**Issue by GustavoGirardelli** [ManimCommunity/manim#3900]
#### Preliminaries

- [ ] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
https://docs.manim.community/en/stable/installation/linux.html#
- [ ] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Installation logs

<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```
$ pip3 install manim
Defaulting to user installation because normal site-packages is not writeable
Collecting manim
  Using cached manim-0.18.1-py3-none-any.whl.metadata (10 kB)
Collecting Pillow>=9.1 (from manim)
  Using cached pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: Pygments>=2.0.0 in /usr/lib/python3/dist-packages (from manim) (2.11.2)
Collecting click>=8.0 (from manim)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cloup>=2.0.0 (from manim)
  Using cached cloup-3.0.5-py2.py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: decorator>=4.3.2 in /usr/lib/python3/dist-packages (from manim) (4.4.2)
Collecting isosurfaces>=0.1.0 (from manim)
  Using cached isosurfaces-0.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting manimpango<1.0.0,>=0.5.0 (from manim)
  Using cached ManimPango-0.5.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Package pangocairo was not found in the pkg-config search path.
      Perhaps you should add the directory containing `pangocairo.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'pangocairo' found
      Traceback (most recent call last):
        File "<string>", line 136, in check_min_version
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['pkg-config', '--print-errors', '--atleast-version', '1.30.0', 'pangocairo']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/gustavo/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/gustavo/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/gustavo/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-97k16acg/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-97k16acg/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-97k16acg/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 203, in <module>
        File "<string>", line 139, in check_min_version
      __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

## System specifications

<details><summary>System Details</summary>

- OS (Ubuntu 22.04.2 LTS): Intel® Core™ i7-4700MQ CPU @ 2.40GHz × 8, Mesa Intel® HD Graphics 4600 (HSW GT2), 64 bits
- RAM: 8.0 GiB
- Python version (`python/py/python3 .10`):
- Installed modules (provide output from `pip list`):
```
$ pip list
Package                      Version
---------------------------- ---------------------
absl-py                      1.4.0
aiohttp                      3.8.4
aiosignal                    1.3.1
anyio                        3.7.0
appdirs                      1.4.4
apturl                       0.5.2
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
arrow                        1.2.3
asgiref                      3.7.2
asttokens                    2.2.1
astunparse                   1.6.3
async-lru                    2.0.2
async-timeout                4.0.2
attrs                        23.1.0
Babel                        2.12.1
backcall                     0.2.0
base58                       2.1.1
bcrypt                       3.2.0
beautifulsoup4               4.10.0
beniget                      0.4.1
bitarray                     2.7.6
bleach                       6.0.0
blinker                      1.6.2
CacheControl                 0.12.10
cached-property              1.5.2
cachetools                   5.3.1
certifi                      2023.5.7
cffi                         1.15.1
chardet                      4.0.0
charset-normalizer           3.1.0
click                        7.1.2
colorama                     0.4.4
comm                         0.1.3
command-not-found            0.3
contourpy                    1.0.7
cryptography                 3.4.8
cssselect                    1.1.0
cupshelpers                  1.0
cycler                       0.11.0
cytoolz                      0.12.1
dbus-python                  1.2.18
debugpy                      1.6.7
decorator                    4.4.2
defer                        1.0.6
defusedxml                   0.7.1
distlib                      0.3.6
distro                       1.7.0
distro-info                  1.0
Django                       5.0
docutils                     0.20.1
duplicity                    0.8.21
edit                         0.0.4
eth-abi                      4.1.0
eth-account                  0.9.0
eth-bloom                    2.0.0
eth-hash                     0.5.2
eth-keyfile                  0.6.1
eth-keys                     0.4.0
eth-rlp                      0.3.0
eth-tester                   0.9.0b2
eth-typing                   3.4.0
eth-utils                    2.2.0
exceptiongroup               1.1.1
executing                    1.2.0
fasteners                    0.14.1
fastjsonschema               2.17.1
ffpyplayer                   4.5.0
filelock                     3.12.0
Flask                        1.1.4
flatbuffers                  23.5.26
fonttools                    4.39.4
fqdn                         1.5.1
frozenlist                   1.4.0
fsspec                       2023.4.0
future                       0.18.2
gast                         0.4.0
google-api-python-client     1.7.11
google-auth                  2.19.1
google-auth-httplib2         0.1.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
greenlet                     1.1.2
grpcio                       1.54.2
h5py                         3.8.0
hexbytes                     0.3.1
html5lib                     1.1
httplib2                     0.20.2
idna                         3.4
importlib-metadata           4.6.4
ipfshttpclient               0.8.0a2
ipykernel                    6.23.1
ipython                      8.13.2
isoduration                  20.11.0
itsdangerous                 1.1.0
jax                          0.4.11
jedi                         0.18.2
jeepney                      0.7.1
Jinja2                       2.11.3
joblib                       1.2.0
json5                        0.9.14
jsonpointer                  2.3
jsonschema                   4.17.3
jupyter_client               8.2.0
jupyter_core                 5.3.0
jupyter-events               0.6.3
jupyter-lsp                  2.2.0
jupyter_server               2.6.0
jupyter_server_terminals     0.4.4
jupyterlab                   4.0.1
jupyterlab-pygments          0.2.2
jupyterlab_server            2.22.1
keras                        2.12.0
keras-nightly                2.14.0.dev2023060107
Keras-Preprocessing          1.1.2
keyring                      23.5.0
Kivy                         2.3.0.dev0
Kivy-examples                2.2.1
Kivy-Garden                  0.1.5
kiwisolver                   1.4.4
language-selector            0.1
launchpadlib                 1.10.16
lazr.restfulclient           0.14.4
lazr.uri                     1.0.6
libclang                     16.0.0
lockfile                     0.12.2
lru-dict                     1.2.0
lxml                         4.8.0
macaroonbakery               1.3.1
Mako                         1.1.3
Markdown                     3.4.3
MarkupSafe                   2.0.1
matplotlib                   3.7.1
matplotlib-inline            0.1.6
mistune                      2.0.5
ml-dtypes                    0.1.0
monotonic                    1.6
more-itertools               8.10.0
mpmath                       1.2.1
msgpack                      1.0.3
multiaddr                    0.0.9
multidict                    6.0.4
mypy-extensions              0.4.4
nbclient                     0.8.0
nbconvert                    7.4.0
nbformat                     5.9.0
nest-asyncio                 1.5.6
netaddr                      0.8.0
netifaces                    0.11.0
networkx                     3.0rc1
notebook_shim                0.2.3
numpy                        1.25.0
nvidia-cublas-cu11           11.11.3.6
nvidia-cudnn-cu11            8.6.0.163
oauth2client                 4.1.3
oauthlib                     3.2.2
odfpy                        1.4.2
olefile                      0.46
opencv-python                4.8.0.74
opt-einsum                   3.3.0
overrides                    7.3.1
packaging                    23.1
pandas                       2.0.2
pandocfilters                1.5.0
paramiko                     2.9.3
parsimonious                 0.9.0
parso                        0.8.3
pbr                          5.8.0
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.0.1
pip                          24.2
pipenv                       2023.5.19
platformdirs                 3.5.1
ply                          3.11
prometheus-client            0.17.0
prompt-toolkit               3.0.38
protobuf                     4.23.2
psutil                       5.9.5
ptyprocess                   0.7.0
pure-eval                    0.2.2
py-ecc                       6.0.0
py-evm                       0.7.0a2
py-geth                      3.13.0
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycairo                      1.20.1
pycparser                    2.21
pycryptodome                 3.18.0
pycups                       2.0.1
PyDrive                      1.3.1
pyenchant                    3.2.0
pyethash                     0.1.27
Pygments                     2.11.2
PyGObject                    3.42.1
PyJWT                        2.3.0
pymacaroons                  0.13.0
PyNaCl                       1.5.0
pyOpenSSL                    21.0.0
pyparsing                    2.4.7
PyPDF2                       3.0.1
PyQt5                        5.15.6
PyQt5-sip                    12.9.1
PyQt6                        6.4.2
PyQt6-Qt6                    6.4.3
PyQt6-sip                    13.4.1
pyRFC3339                    1.1
pyrsistent                   0.19.3
pyserial                     3.5
python-apt                   2.4.0+ubuntu1
python-dateutil              2.8.2
python-debian                0.1.49
python-dotenv                1.0.0
python-json-logger           2.0.7
python-sane                  2.9.1
pythran                      0.10.0
pytz                         2024.1
pyunormalize                 15.0.0
pyxdg                        0.27
PyYAML                       5.4.1
pyzmq                        25.1.0
regex                        2023.6.3
reportlab                    3.6.8
requests                     2.31.0
requests-oauthlib            1.3.1
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rlp                          3.0.0
rsa                          4.9
safe-pysha3                  1.0.4
scikit-learn                 1.2.2
scipy                        1.10.1
scour                        0.38.2
SecretStorage                3.3.1
semantic-version             2.10.0
Send2Trash                   1.8.2
sentry-sdk                   1.4.3
setuptools                   68.0.0
Shapely                      1.8.0
six                          1.16.0
sniffio                      1.3.0
sortedcontainers             2.4.0
soupsieve                    2.3.1
SQLAlchemy                   1.4.31
sqlalchemy-migrate           0.13.0
sqlparse                     0.4.4
stack-data                   0.6.2
sympy                        1.11.1
systemd-python               234
tb-nightly                   2.14.0a20230601
Tempita                      0.5.2
tensorboard                  2.12.3
tensorboard-data-server      0.7.0
tensorflow                   2.12.0
tensorflow-addons            0.20.0
tensorflow-estimator         2.12.0
tensorflow-io-gcs-filesystem 0.32.0
termcolor                    2.3.0
terminado                    0.17.1
testresources                2.0.1
tf-estimator-nightly         2.14.0.dev2023060108
tf-nightly                   2.14.0.dev20230601
threadpoolctl                3.1.0
tinycss2                     1.2.1
tomli                        2.0.1
toolz                        0.12.0
torch                        2.1.0.dev20230601+cpu
tornado                      6.3.2
traitlets                    5.9.0
trie                         2.1.1
typeguard                    2.13.3
typing_extensions            4.5.0
tzdata                       2023.3
ubuntu-advantage-tools       8001
ubuntu-drivers-common        0.0.0
ufw                          0.36.1
unattended-upgrades          0.1
unittest2                    1.1.0
uri-template                 1.2.0
uritemplate                  3.0.1
urllib3                      1.26.16
usb-creator                  0.3.7
varint                       1.0.2
virtualenv                   20.23.1
virtualenv-clone             0.5.7
wadllib                      1.3.6
wcwidth                      0.2.6
web3                         6.6.1
webcolors                    1.13
webencodings                 0.5.1
websocket-client             1.5.2
websockets                   11.0.3
Werkzeug                     1.0.1
wheel                        0.40.0
wrapt                        1.14.1
xdg                          5
xkit                         0.0.0
yarl                         1.9.2
zipp                         1.0.0

```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

**Comment by uwezi** [comment]
can't you give your issue a descriptive title?

According to a very recent discussion on Discord the following might help your with your pango/cairo installation problem on Ubuntu:

```
sudo apt update
sudo apt install libcairo2-dev libpango1.0-dev
```
