### ISSUE TITLE
Error when installing on apple silicon mac

### ISSUE THREAD

**Issue by abhigyanj** [ManimCommunity/manim#3952]
## Description of error
I've installed all the required dependencies for macOS mentioned on https://docs.manim.community/en/stable/installation/macos.html but when I try to install manim via `pip`, I get the following error: 

```
...
Collecting manimpango<0.5.0,>=0.4.0.post0 (from manim)
  Using cached ManimPango-0.4.4.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/abhigyanj/Documents/Programming/Python Learning/3b1b/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/abhigyanj/Documents/Programming/Python Learning/3b1b/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/abhigyanj/Documents/Programming/Python Learning/3b1b/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/32/wr9q6vq15n12d_r6zn21lpq80000gn/T/pip-build-env-7vh801uw/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/32/wr9q6vq15n12d_r6zn21lpq80000gn/T/pip-build-env-7vh801uw/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/32/wr9q6vq15n12d_r6zn21lpq80000gn/T/pip-build-env-7vh801uw/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 42, in <module>
        File "<string>", line 38, in get_version
      KeyError: '__version__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

## System specifications

<details><summary>System Details</summary>

- OS: macOS 15.1
- RAM: 16GB
- Python version: Python 3.13.0
- Installed modules (using venv):
- Chip: M1
```
Package Version
------- -------
pip     24.2
```
</details>

Extra details: When I try installing the latest version of `manimpango`, it installs

**Comment by behackl** [comment]
This appears to be an issue with Python 3.13. The version restriction imposed on manimpango (`>=0.4.0.post0, <0.5.0`) seem a bit odd, though. Can you share the full log output of `pip install`?

The easiest way to get the install up and going on your machine is either directly brew-installing manim (`brew install manim`), or pip-installing it with a Python version of at most 3.12, until we manage to release a new version where this is fixed.

**Comment by nhabedi** [comment]
I had the same problem on Windows and I can confirm that downgrading from Python 3.13 to 3.12 solves the issue.

**Comment by fluxxion82** [comment]
ditto...not using Python 3.13 worked for me too

**Comment by akirpach** [comment]
Second @nhabedi 's respond,

I installed `python3.12 -m venv new_venv` new virtual environment and then pip3 install manim there. Works without issues.

**Comment by thomasgundt** [comment]
could someone possibly add this solution as a note to the community website? https://docs.manim.community/en/stable/installation/macos.html
