### ISSUE TITLE
Issue getting requirements to build wheel

### ISSUE THREAD

**Issue by randy-shi** [ManimCommunity/manim#3978]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://docs.manim.community/en/stable/installation.html).
- [x] I have checked the [installation FAQ](https://docs.manim.community/en/stable/faq/installation.html) and my problem is either not mentioned there,
      or the solution given there does not help.

## Description of error
I was going through the manual installation steps when I encountered this issue. I've already install FFmpeg and added it to PATH, but when I tried using pip to install manim, it gave me this error.

## Installation logs

<details><summary>Terminal output</summary>

```
Collecting manim
  Using cached manim-0.14.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: Pillow in c:\users\shira\appdata\local\programs\python\python313\lib\site-packages (from manim) (11.0.0)
Collecting click>=7.1 (from manim)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting click-default-group (from manim)
  Using cached click_default_group-1.2.4-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting cloup<0.8.0,>=0.7.0 (from manim)
  Using cached cloup-0.7.1-py2.py3-none-any.whl.metadata (7.8 kB)
Collecting colour (from manim)
  Using cached colour-0.1.5-py2.py3-none-any.whl.metadata (18 kB)
Collecting decorator<6.0.0,>=5.0.7 (from manim)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting isosurfaces==0.1.0 (from manim)
  Using cached isosurfaces-0.1.0-py3-none-any.whl.metadata (2.9 kB)
Collecting manimpango<0.5.0,>=0.4.0.post0 (from manim)
  Using cached ManimPango-0.4.4.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\shira\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\shira\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shira\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\shira\AppData\Local\Temp\pip-build-env-zh1ozcn2\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shira\AppData\Local\Temp\pip-build-env-zh1ozcn2\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\shira\AppData\Local\Temp\pip-build-env-zh1ozcn2\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 42, in <module>
        File "<string>", line 38, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 11
- RAM: 32 GB
- Python version (`python/py/python3 --version`): 3.13
- Installed modules (provide output from `pip list`): ffmpeg        1.4
MouseInfo     0.1.3
mpmath        1.3.0
numpy         2.1.2
opencv-python 4.10.0.84
packaging     24.1
pillow        11.0.0
pip           24.2
PyAutoGUI     0.9.54
PyGetWindow   0.0.9
PyMsgBox      1.0.9
pyperclip     1.9.0
PyRect        0.2.0
PyScreeze     1.0.1
pytesseract   0.3.13
pytweening    1.2.0
sympy         1.13.3
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): MikTex
+ Installed LaTeX packages:
 ![image](https://github.com/user-attachments/assets/540b28b4-d609-4173-b24c-41aead5cc38d)
</details>

**Comment by randy-shi** [comment]
Just used choco instead
