### ISSUE TITLE
LaTeX compilation failed on windows 11

### ISSUE THREAD

**Issue by hengaini2055** [ManimCommunity/manim#4075]
## How to reproduce the issue
I have installed the manin in windows 11 and correct. Directly (Windows) stage.
When I run the command: `manimgl example_scenes.py OpeningManimExample`, the windows open and last for about 5 seconds and dispear.
The output as follows:

```
PS C:\Users\henga\manim> manimgl example_scenes.py OpeningManimExample
ManimGL v1.7.2
Traceback (most recent call last):d \\\quad \\\end{array}\right]...
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Program Files\Python\Python311\Scripts\manimgl.exe\__main__.py", line 7, in <module>
  File "C:\Users\henga\manim\manimlib\__main__.py", line 61, in main
    run_scenes()
  File "C:\Users\henga\manim\manimlib\__main__.py", line 39, in run_scenes
    scene.run()
  File "C:\Users\henga\manim\manimlib\scene\scene.py", line 155, in run
    self.construct()
  File "C:\Users\henga\manim\example_scenes.py", line 29, in construct
    IntegerMatrix(matrix),
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\mobject\matrix.py", line 245, in __init__
    super().__init__(matrix, num_decimal_places, decimal_config, **config)
  File "C:\Users\henga\manim\manimlib\mobject\matrix.py", line 224, in __init__
    super().__init__(
  File "C:\Users\henga\manim\manimlib\mobject\matrix.py", line 59, in __init__
    self.brackets = self.create_brackets(self.rows, bracket_v_buff, bracket_h_buff)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\mobject\matrix.py", line 120, in create_brackets
    brackets = Tex("".join((
               ^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\mobject\svg\tex_mobject.py", line 59, in __init__
    super().__init__(
  File "C:\Users\henga\manim\manimlib\mobject\svg\string_mobject.py", line 69, in __init__
    svg_string = self.get_svg_string()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\mobject\svg\string_mobject.py", line 77, in get_svg_string
    return self.get_svg_string_by_content(content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\mobject\svg\tex_mobject.py", line 70, in get_svg_string_by_content
    return latex_to_svg(content, self.template, self.additional_preamble, short_tex=self.tex_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\utils\tex_file_writing.py", line 81, in latex_to_svg
    return full_tex_to_svg(full_tex, compiler, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\utils\cache.py", line 27, in wrapper
    value = func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henga\manim\manimlib\utils\tex_file_writing.py", line 127, in full_tex_to_svg
    raise LatexError(error_str or "LaTeX compilation failed")
manimlib.utils.tex_file_writing.LatexError: LaTeX compilation failed
```
I have installed python 311, and can run `python311` to run. But when I run `python`, the OS open windows store. This may be a reason.

</details>

## Additional media files

<details><summary>Images/GIFs</summary>

![image](https://github.com/user-attachments/assets/008417bf-3c96-462d-8294-89a78e82ffe8)
![image](https://github.com/user-attachments/assets/29f0ceae-a338-4336-93fa-2d2275734f30)
</details>

## Logs
<details><summary>Terminal output</summary>

```
PASTE HERE OR PROVIDE LINK TO https://pastebin.com/ OR SIMILAR
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 11
- RAM: 64G
- Python version (`python/py/python3 --version`): Python 3.11.5
- Installed modules (provide output from `pip list`):
```
Package                      Version     Editable project location
---------------------------- ----------- -------------------------
absl-py                      2.1.0
addict                       2.4.0
annotated-types              0.7.0
anyio                        4.6.2.post1
appdirs                      1.4.4
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
asttokens                    3.0.0
astunparse                   1.6.3
attrs                        24.2.0
beautifulsoup4               4.12.3
bleach                       6.1.0
blis                         1.0.1
bokeh                        3.4.2
BPMN-RPA                     9.2.5
bs4                          0.0.2
cached-property              2.0.1
catalogue                    2.0.10
certifi                      2024.6.2
cffi                         1.17.1
charset-normalizer           3.3.2
click                        8.1.7
cloudpathlib                 0.20.0
colorama                     0.4.6
colour                       0.1.5
confection                   0.1.5
construct                    2.10.70
contourpy                    1.2.1
cryptography                 43.0.3
cycler                       0.12.1
cymem                        2.0.8
data                         0.4
decorator                    5.1.1
defusedxml                   0.7.1
dill                         0.3.9
diskcache                    5.6.3
distro                       1.9.0
dnspython                    2.7.0
exchangelib                  5.5.0
executing                    2.1.0
flatbuffers                  24.3.25
fonttools                    4.55.0
funcsigs                     1.0.2
future                       1.0.0
gast                         0.6.0
glcontext                    3.0.0
google-pasta                 0.2.0
grpcio                       1.68.0
h11                          0.14.0
h5py                         3.12.1
httpcore                     1.0.7
httpx                        0.27.2
idna                         3.7
ipython                      8.31.0
isodate                      0.7.2
isosurfaces                  0.1.2
jedi                         0.19.2
Jinja2                       3.1.4
jira                         3.8.0
jiter                        0.7.1
keras                        3.6.0
keyboard                     0.13.5
kiwisolver                   1.4.7
langcodes                    3.4.1
language_data                1.2.0
latex                        0.7.0
libclang                     18.1.1
linkify-it-py                2.0.3
lxml                         5.3.0
manimgl                      1.7.2       C:\Users\henga\manim
ManimPango                   0.6.0
mapbox_earcut                1.0.3
marisa-trie                  1.2.1
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.2
matplotlib-inline            0.1.7
mdit-py-plugins              0.4.1
mdurl                        0.1.2
ml-dtypes                    0.4.1
moderngl                     5.12.0
moderngl-window              3.0.3
MouseInfo                    0.1.3
mpmath                       1.3.0
msal                         1.31.0
murmurhash                   1.0.10
namex                        0.0.8
numpy                        2.0.0
oauthlib                     3.2.2
openai                       1.54.4
opt_einsum                   3.4.0
optree                       0.13.1
outcome                      1.3.0.post0
packaging                    24.1
pandas                       2.2.2
panel                        1.4.4
param                        2.1.1
parso                        0.8.4
pillow                       10.3.0
pip                          24.3.1
preshed                      3.0.9
prompt_toolkit               3.0.48
protobuf                     5.28.3
psycopg2-binary              2.9.10
pure_eval                    0.2.3
PyAutoGUI                    0.9.54
pycparser                    2.22
pycryptodomex                3.21.0
pydantic                     2.9.2
pydantic_core                2.23.4
pydub                        0.25.1
PyGetWindow                  0.0.9
pyglet                       2.0.20
PyGLM                        2.7.3
Pygments                     2.18.0
PyJWT                        2.9.0
pykeepass                    4.1.0.post1
PyMsgBox                     1.0.9
pyodbc                       5.2.0
PyOpenGL                     3.1.7
pyparsing                    3.2.0
PyPDF2                       3.0.1
pyperclip                    1.9.0
pypiwin32                    223
PyRect                       0.2.0
PyScreeze                    1.0.1
PySocks                      1.7.1
pyspnego                     0.11.2
python-dateutil              2.9.0.post0
pytweening                   1.2.0
pytz                         2024.1
pyviz_comms                  3.0.2
pywin32                      306
PyYAML                       6.0.1
requests                     2.32.3
requests_ntlm                1.3.0
requests-oauthlib            2.0.0
requests-toolbelt            1.0.0
rich                         13.9.4
scipy                        1.14.1
screeninfo                   0.8.1
selenium                     4.26.1
setuptools                   65.5.0
shellingham                  1.5.4
shutilwhich                  1.1.0
six                          1.16.0
skia-pathops                 0.8.0.post2
smart-open                   7.0.5
sniffio                      1.3.1
sortedcontainers             2.4.0
soupsieve                    2.6
spacy                        3.8.2
spacy-legacy                 3.0.12
spacy-loggers                1.0.5
srsly                        2.4.8
sspilib                      0.2.0
stack-data                   0.6.3
svgelements                  1.9.6
sympy                        1.13.3
tempdir                      0.7.1
tensorboard                  2.18.0
tensorboard-data-server      0.7.2
tensorflow                   2.18.0
tensorflow_intel             2.18.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.5.0
thinc                        8.3.2
tornado                      6.4.1
tqdm                         4.66.4
traitlets                    5.14.3
trio                         0.27.0
trio-websocket               0.11.1
typer                        0.13.0
typing_extensions            4.12.2
tzdata                       2024.1
tzlocal                      5.2
uc-micro-py                  1.0.3
urllib3                      2.2.2
validators                   0.34.0
wasabi                       1.1.3
wcwidth                      0.2.13
weasel                       0.4.1
webencodings                 0.5.1
websocket-client             1.8.0
Werkzeug                     3.1.3
wheel                        0.45.0
wrapt                        1.16.0
wsproto                      1.2.0
xmltodict                    0.14.2
xyzservices                  2024.6.0
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):This is pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.10) (preloaded format=latex.fmt)
 restricted \write18 enabled.
+ Installed LaTeX packages:

![image](https://github.com/user-attachments/assets/5992cd14-cbe9-4090-9ecc-6dfa039d63ce)

</details>

**Comment by uwezi** [comment]
You placed a bug-report on the Github for ManimCE, but you are apparently using ManimGL. These are two different editions of Manim, see https://docs.manim.community/en/stable/faq/installation.html

Also see the Github of ManimGL https://github.com/3b1b/manim

**Comment by T-freedom** [comment]
Is it solved?

**Comment by woodysseus** [comment]
the same issue, waiting for any tips, thanks

**Comment by JasonGrace2282** [comment]
Closing as this issue is about ManimGL. If you still need help, see [the faq](https://docs.manim.community/en/stable/faq/help.html)
