### ISSUE TITLE
Unable to render SVG image

### ISSUE THREAD

**Issue by AkashKarnatak** [ManimCommunity/manim#437]
I am not able to render this SVG image using SVGMobject. Here's my code 
[SmileOpen1.zip](https://github.com/ManimCommunity/manim/files/5213542/SmileOpen1.zip)

```py
class Assemble(Scene):
    def construct(self):
        svg = SVGMobject('SmileOpen1')
        self.add(svg)
```
The error message, 
```sh
Traceback (most recent call last):
  File "/home/akash/GitHub/manim-ce/manim/__main__.py", line 166, in main
    scene = SceneClass()
  File "/home/akash/GitHub/manim-ce/manim/scene/scene.py", line 82, in __init__
    self.construct()
  File "test.py", line 5, in construct
    svg = SVGMobject('SmileOpen1')
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 49, in __init__
    VMobject.__init__(self, **kwargs)
  File "/home/akash/GitHub/manim-ce/manim/mobject/mobject.py", line 62, in __init__
    self.generate_points()
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 71, in generate_points
    mobjects = self.get_mobjects_from(svg)
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 88, in get_mobjects_from
    *[self.get_mobjects_from(child) for child in element.childNodes]
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 88, in <listcomp>
    *[self.get_mobjects_from(child) for child in element.childNodes]
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 88, in get_mobjects_from
    *[self.get_mobjects_from(child) for child in element.childNodes]
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 88, in <listcomp>
    *[self.get_mobjects_from(child) for child in element.childNodes]
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 93, in get_mobjects_from
    result.append(self.path_string_to_mobject(temp))
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 120, in path_string_to_mobject
    return VMobjectFromSVGPathstring(path_string)
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 314, in __init__
    VMobject.__init__(self, **kwargs)
  File "/home/akash/GitHub/manim-ce/manim/mobject/mobject.py", line 62, in __init__
    self.generate_points()
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 343, in generate_points
    self.handle_command(command, coord_string)
  File "/home/akash/GitHub/manim-ce/manim/mobject/svg/svg_mobject.py", line 413, in handle_command
    self.add_cubic_bezier_curve_to(*new_points[i : i + 3])
TypeError: add_cubic_bezier_curve_to() missing 1 required positional argument: 'anchor'
```

**Comment by leotrs** [comment]
Thanks for reporting this, @AkashKarnatak . There are many existing bugs in SVG rendering. We are working on them ;) cc. @yoshiask

**Comment by leotrs** [comment]
As we have currently no one working on improving SVG support, and it is not one of our current priorities, I am closing this issue for the time being.

This issue will be reopened when someone takes on the challenge to improve SVG support.

All issues (open or closed) related to SVG support can be found [in the SVG project board](https://github.com/ManimCommunity/manim/projects/8#card-49797664).
