### ISSUE TITLE
 [BUG-General] ModuleNotFoundError: No module named 'pangocairocffi._generated.ffi'

### ISSUE THREAD

**Issue by daljit97** [ManimCommunity/manim#689]
Hi I have tried to run a simple example on Fedora 32. However when I try to run the example I get the following:
```

Traceback (most recent call last):
  File "/home/daljit97/PycharmProjects/Topology/venv/bin/manim", line 5, in <module>
    from manim.__main__ import main
  File "/home/daljit97/PycharmProjects/Topology/venv/lib64/python3.8/site-packages/manim/__init__.py", line 47, in <module>
    from .mobject.svg.text_mobject import *
  File "/home/daljit97/PycharmProjects/Topology/venv/lib64/python3.8/site-packages/manim/mobject/svg/text_mobject.py", line 13, in <module>
    import pangocairocffi
  File "/home/daljit97/PycharmProjects/Topology/venv/lib64/python3.8/site-packages/pangocairocffi/__init__.py", line 11, in <module>
    from ._generated.ffi import ffi
ModuleNotFoundError: No module named 'pangocairocffi._generated.ffi'

```

I have already installed the `pangocairocffi` package and the installation of `manimce` didn't show any error.

**Comment by leotrs** [comment]
Thanks for reporting. Please see [this link](https://docs.manim.community/en/latest/installation/troubleshooting.html#modulenotfounderror-no-module-named-generated-ffi) and report back whether or not it worked.

**Comment by daljit97** [comment]
Thanks I was able to make this work, but to had to manually build the bindings as suggested in your link.

**Comment by behackl** [comment]
Excellent, good to hear! We hope to have this issue resolved soon; for now the workaround has to be used unfortunately.
