### ISSUE TITLE
Running manim without any flags or render commands throws an error [BUG-General]  

### ISSUE THREAD

**Issue by XorUnison** [ManimCommunity/manim#690]
It seems as if currently running just `manim` without any flag or scene to render it throws the following error:
```Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\manim.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\manim\__main__.py", line 47, in main
    args = parse_args(sys.argv)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\manim\_config\main_utils.py", line 110, in parse_args
    subcmd = _find_subcommand(args)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\manim\_config\main_utils.py", line 39, in _find_subcommand
    subcmd = args[1]
IndexError: list index out of range
```

@behackl has mentioned seeing the same bahaviour.
This isn't a major issue since otherwise everything seems to run fine (can still use `manim -h` or render scenes), but somehow who might know what's going on should have a look into it.

**Comment by leotrs** [comment]
This is 99% probably my fault (#340)
