### ISSUE TITLE
Error on installation while collecting pangocairocffi

### ISSUE THREAD

**Issue by ANearchou** [ManimCommunity/manim#808]
I'm getting the following error while installing with ``` pip install manimce```

## Installation logs

<details><summary>Terminal output</summary>

```
 ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-m5ldpfmz\\pangocairocffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-m5ldpfmz\\pangocairocffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-m5ldpfmz\pangocairocffi\
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-m5ldpfmz\pangocairocffi\setup.py", line 12, in <module>
        'pangocairocffi/ffi_build.py:ffi'
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\user\appdata\local\programs\python\python37\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "c:\users\user\appdata\local\programs\python\python37\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py", line 739, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\cffi\setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "pangocairocffi/ffi_build.py", line 11, in <module>
        from pangocffi.ffi_instance_builder import \
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pangocffi\__init__.py", line 19, in <module>
        pango = _dlopen(ffi, 'pango', 'pango-1', 'pango-1.0', 'pango-1.0-0')
      File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pangocffi\__init__.py", line 16, in _dlopen
        raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
    OSError: dlopen() failed to load a library: pango / pango-1 / pango-1.0 / pango-1.0-0
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

</details>

I follow the instructions found here ```https://docs.manim.community/en/stable/installation/troubleshooting.html``` however I cannot find the ```zlib1.dll``` file under the path ```C:\Program Files\Intel\Wifi\bin```. Instead I found this file under my git path. Renaming it does not solve the problem.

I also have already installed and working just fine with ```3b1b/manim```

## System specifications

<details><summary>System Details</summary>

- OS Windows 10 Home
- Python version 3.7.4
- Installed modules :

```
Package           Version
----------------- --------
cairocffi         1.2.0
cffi              1.14.4
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
grpcio            1.33.2
grpcio-tools      1.33.2
mpmath            1.1.0
numpy             1.16.4
opencv-python     3.4.2.17
pandas            1.1.4
pangocffi         0.6.0
pathtools         0.1.2
Pillow            5.2.0
pip               19.2.2
progressbar       2.5
protobuf          3.14.0
pycairo           1.20.0
pycparser         2.20
pydub             0.23.0
Pygments          2.6.1
pyreadline        2.1
python-dateutil   2.8.1
pytz              2020.4
rich              9.3.0
scipy             1.3.0
setuptools        40.8.0
six               1.15.0
tqdm              4.24.0
typing-extensions 3.7.4.3
watchdog          0.10.4
```
</details>

Any help is appreciated and thank you in advance!

**Comment by leotrs** [comment]
Hello @ANearchou and thanks for reporting. Unfortunately, installing manim on windows is still something we have to figure out completely. I will ping our windows team to see if they can help you out cc @ManimCommunity/windows 

Have you considered using alternatives? For windows, you can use the chocolatey package or the dockerfile.

**Comment by naveen521kk** [comment]
Did you follow instruction [here](https://docs.manim.community/en/stable/installation/win.html#pango-installation)? Added it to the path? Alternatively, chocolatey do it from you. See [here](https://docs.manim.community/en/stable/installation/win.html#installing-using-chocolatey).

**Comment by ANearchou** [comment]
I didn't think that I would need any more dependencies since I was working with 3b1b/manim. I just downloaded Pango and then ```pip install manimce```. It's working perfectly! 
Thanks a lot!

**Comment by cobordism** [comment]
> It's working perfectly!

cool.
for future reference, I think we're moving to just `pip install manim` in future.
