### ISSUE TITLE
Trying to render short Arabic Text

### ISSUE THREAD

**Issue by TechnocracyArabic** [ManimCommunity/manim#882]
## Description of bug / unexpected behaviour
Trying to render a Scene with one word Arabic `Text` but give an error without rendering any scene.
Though, rendering the Scene with two Arabic words or one long word work fine.

## Expected behaviour
Rendering a Scene with the Arabic text with the desirable font whether it is small one word or multiple long words.

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
class Test(Scene):
    def construct(self):
        Test = Text("محمد", font="Adobe Arabic")
        Test1 = Text("خالد", font="Adobe Arabic")
        
        self.play(Write(Test))
        self.play(Write(Test1))
        self.wait(2)
```

</details>

## Logs
<details><summary>Terminal output</summary>

```
Traceback (most recent call last):
  File "C:\tools\Manim\Lib\site-packages\manim\__main__.py", line 84, in main
    scene.render()
  File "C:\tools\Manim\Lib\site-packages\manim\scene\scene.py", line 90, in render
    self.construct()
  File "example.py", line 80, in construct
    self.play(Write(Test1))
  File "C:\tools\Manim\Lib\site-packages\manim\animation\creation.py", line 146, in __init__
    self.set_default_config_from_length(mobject)
  File "C:\tools\Manim\Lib\site-packages\manim\animation\creation.py", line 157, in set_default_config_from_length
    self.lag_ratio = min(4.0 / length, 0.2)
ZeroDivisionError: float division by zero
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS: Windows 10 Pro
- RAM: 16GB
- Python version: 3.8.6
- Installed modules (provide output from `pip list`):
```
astroid           2.4.2
cairocffi         1.2.0
cffi              1.14.4
colorama          0.4.4
colour            0.1.5
commonmark        0.9.1
isort             5.6.4
lazy-object-proxy 1.4.3
manimce           0.1.1
mccabe            0.6.1
numpy             1.19.3
pangocairocffi    0.4.0
pangocffi         0.8.0
Pillow            8.0.1
pip               20.3.3
progressbar       2.5
pycairo           1.20.0
pycparser         2.20
pydub             0.24.1
Pygments          2.7.3
pylint            2.6.0
rich              6.2.0
scipy             1.5.4
setuptools        49.2.1
six               1.15.0
toml              0.10.2
tqdm              4.55.0
typing-extensions 3.7.4.3
wheel             0.36.2
wrapt             1.12.1
```
</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version N-94421-gb3b7523feb Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9.1.1 (GCC) 20190716
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 32.100 / 56. 32.100
libavcodec     58. 55.100 / 58. 55.100
libavformat    58. 30.100 / 58. 30.100
libavdevice    58.  9.100 / 58.  9.100
libavfilter     7. 58.100 /  7. 58.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100
```
</details>

**Comment by leotrs** [comment]
Thanks for reporting!

@naveen521kk this sounds like the submobject arithmetic is making a wrong assumption somewhere. What do you think?

**Comment by naveen521kk** [comment]
I had some debugging on this yesterday when he originally reported this on [discord](https://discord.com/channels/581738731934056449/582403919754297363/793177765423087618). I found that the rendered SVG had nothing in it, it was just an empty SVG when the font is passed. I think something is going wrong in our setup and it needs a little more investigation. 

It is just the part on `Text` and not any other thing.

**Comment by behackl** [comment]
As far as I am aware, this should work since we've migrated to using Pango. Closing.
