### ISSUE TITLE
ManimConfig Write Bug

### ISSUE THREAD

**Issue by jsonvillanueva** [ManimCommunity/manim#973]
## Description of bug / unexpected behavior

```
(manim) C:\Users\a\Documents\repos\ManimCommunity\manim>manim cfg export
You are reading the config from the same directory you are exporting to.
This means that the exported config will overwrite the config for this directory.
Are you sure you want to continue? (y/n)y
Traceback (most recent call last):
  File "C:\Users\a\anaconda3\envs\manim\Scripts\manim", line 5, in <module>
    main()
  File "C:\Users\a\Documents\repos\ManimCommunity\manim\manim\__main__.py", line 65, in main
    cfg_subcmds.export(args.dir)
  File "C:\Users\a\Documents\repos\ManimCommunity\manim\manim\_config\cfg_subcmds.py", line 245, in export
    config.write(outpath)
AttributeError: 'ManimConfig' object has no attribute 'write'
```
```
(manim) C:\Users\a\Documents\repos\ManimCommunity\manim>manim cfg export --dir test
Creating folder: test.
Traceback (most recent call last):
  File "C:\Users\a\anaconda3\envs\manim\Scripts\manim", line 5, in <module>
    main()
  File "C:\Users\a\Documents\repos\ManimCommunity\manim\manim\__main__.py", line 65, in main
    cfg_subcmds.export(args.dir)
  File "C:\Users\a\Documents\repos\ManimCommunity\manim\manim\_config\cfg_subcmds.py", line 245, in export
    config.write(outpath)
AttributeError: 'ManimConfig' object has no attribute 'write'

```
## Expected behavior
A manim.cfg file populated at the specified directory (defaults to cwd).

## How to reproduce the issue

Clone the master branch and run as I did in the CLI above:
`manim cfg export`
`manim cfg export --dir test`

## System specifications
- OS (with version, e.g Windows 10 v2004 or macOS 10.15 (Catalina)):

## Additional comments
This also seems to be in the case in Ubuntu 20.04 as tested by @huguesdevimeux

**Comment by huguesdevimeux** [comment]
cc @Aathish04, author of `cfg` command (a while ago, so maybe it's outdated)
